#!/usr/bin/env bash
#  -------------------------------------------------------------------------------------
#
#  Description:  This file holds countless aliases for most used programs
#
#  Sections:
#  1.   Git
#  2.   kubectl
#
#  -------------------------------------------------------------------------------------

#   ---------------------------
#   1. GIT
#   ---------------------------
alias g='git'

alias ga='git add'
alias gaa='git add --all'
alias gapa='git add --patch'
alias gau='git add --update'

alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbda='git branch --no-color --merged | command grep -vE "^(\*|\s*(master|develop|dev)\s*$)" | command xargs -n 1 git branch -d'
alias gbl='git blame -b -w'
alias gbnm='git branch --no-merged'
alias gbr='git branch --remote'
alias gbs='git bisect'
alias gbsb='git bisect bad'
alias gbsg='git bisect good'
alias gbsr='git bisect reset'
alias gbss='git bisect start'

alias gc='git commit -v'
alias gc!='git commit -v --amend'
alias gcn!='git commit -v --no-edit --amend'
alias gca='git commit -v -a'
alias gca!='git commit -v -a --amend'
alias gcan!='git commit -v -a --no-edit --amend'
alias gcans!='git commit -v -a -s --no-edit --amend'
alias gcam='git commit -a -m'
alias gcsm='git commit -s -m'
alias gcb='git checkout -b'
alias gcf='git config --list'
alias gcl='git clone --recursive'
alias gclean='git clean -fd'
alias gpristine='git reset --hard && git clean -dfx'
alias gcm='git checkout master'
alias gcd='git checkout develop'
alias gcmsg='git commit -m'
alias gco='git checkout'
alias gcount='git shortlog -sn'
#compdef _git gcount complete -F _git gcount
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gcs='git commit -S'

alias gd='git diff'
alias gdca='git diff --cached'
alias gdct='git describe --tags `git rev-list --tags --max-count=1`'
alias gdt='git diff-tree --no-commit-id --name-only -r'
alias gdw='git diff --word-diff'

gdv() {
  git diff -w "$@" | view -
}
#compdef _git gdv=git-diff

alias gf='git fetch'
alias gfa='git fetch --all --prune'
alias gfo='git fetch origin'

gfg() {
  git ls-files | grep "$@"
}
#compdef _grep gfg

alias gg='git gui citool'
alias gga='git gui citool --amend'

ggf() {
  [[ "$#" != 1 ]] && local b="$(git_current_branch)"
  git push --force origin "${b:=$1}"
}
#compdef _git ggf=git-checkout

ggl() {
  if [[ "$#" != 0 ]] && [[ "$#" != 1 ]]; then
    git pull origin "${*}"
  else
    [[ "$#" == 0 ]] && local b="$(git_current_branch)"
    git pull origin "${b:=$1}"
  fi
}
#compdef _git ggl=git-checkout

ggp() {
  if [[ "$#" != 0 ]] && [[ "$#" != 1 ]]; then
    git push origin "${*}"
  else
    [[ "$#" == 0 ]] && local b="$(git_current_branch)"
    git push origin "${b:=$1}"
  fi
}
#compdef _git ggp=git-checkout

ggpnp() {
  if [[ "$#" == 0 ]]; then
    ggl && ggp
  else
    ggl "${*}" && ggp "${*}"
  fi
}
#compdef _git ggpnp=git-checkout

ggu() {
  [[ "$#" != 1 ]] && local b="$(git_current_branch)"
  git pull --rebase origin "${b:=$1}"
}
#compdef _git ggu=git-checkout

alias ggpur='ggu'
#compdef _git ggpur=git-checkout

alias ggpull='git pull origin $(git_current_branch)'
#compdef _git ggpull=git-checkout

alias ggpush='git push origin $(git_current_branch)'
#compdef _git ggpush=git-checkout

alias ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'
alias gpsup='git push --set-upstream origin $(git_current_branch)'

alias ghh='git help'

alias gignore='git update-index --assume-unchanged'
alias gignored='git ls-files -v | grep "^[[:lower:]]"'
alias git-svn-dcommit-push='git svn dcommit && git push github master:svntrunk'
#compdef _git git-svn-dcommit-push=git

alias gk='\gitk --all --branches'
#compdef _git gk='gitk'
alias gke='\gitk --all $(git log -g --pretty=%h)'
#compdef _git gke='gitk'

alias gl='git pull'
alias glg='git log --stat'
alias glgp='git log --stat -p'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glgm='git log --graph --max-count=10'
alias glo='git log --oneline --decorate'
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glola="git log --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all"
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias glp="_git_log_prettily"
#compdef _git glp=git-log

alias gm='git merge'
alias gmom='git merge origin/master'
alias gmt='git mergetool --no-prompt'
alias gmtvim='git mergetool --no-prompt --tool=vimdiff'
alias gmum='git merge upstream/master'

alias gp='git push'
alias gpd='git push --dry-run'
alias gpoat='git push origin --all && git push origin --tags'
#compdef _git gpoat=git-push
alias gpu='git push upstream'
alias gpv='git push -v'

alias gr='git remote'
alias gra='git remote add'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbm='git rebase master'
alias grbs='git rebase --skip'
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias grmv='git remote rename'
alias grrm='git remote remove'
alias grset='git remote set-url'
alias grt='cd $(git rev-parse --show-toplevel || echo ".")'
alias gru='git reset --'
alias grup='git remote update'
alias grv='git remote -v'

alias gsb='git status -sb'
alias gsd='git svn dcommit'
alias gsi='git submodule init'
alias gsps='git show --pretty=short --show-signature'
alias gsr='git svn rebase'
alias gss='git status -s'
alias gst='git status'
alias gsta='git stash save'
alias gstaa='git stash apply'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show --text'
alias gsu='git submodule update'

alias gts='git tag -s'
alias gtv='git tag | sort -V'

alias gunignore='git update-index --no-assume-unchanged'
alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
alias gup='git pull --rebase'
alias gupv='git pull --rebase -v'
alias glum='git pull upstream master'

alias gwch='git whatchanged -p --abbrev-commit --pretty=medium'
alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify -m "--wip-- [skip ci]"'


#   ---------------------------
#   2. KUBECTL
#   ---------------------------
alias k='kubectl'

alias ka='kubectl apply --recursive -f'

alias kd='kubectl describe'
alias kdall='kubectl describe --all-namespaces'
alias kdcm='kubectl describe configmap'
alias kdcmall='kubectl describe configmap --all-namespaces'
alias kdcml='kubectl describe configmap -l'
alias kdcmn='kubectl describe configmap --namespace'
alias kddep='kubectl describe deployment'
alias kddepall='kubectl describe deployment --all-namespaces'
alias kddepl='kubectl describe deployment -l'
alias kddepn='kubectl describe deployment --namespace'
alias kdf='kubectl describe --recursive -f'
alias kding='kubectl describe ingress'
alias kdingall='kubectl describe ingress --all-namespaces'
alias kdingl='kubectl describe ingress -l'
alias kdingn='kubectl describe ingress --namespace'
alias kdl='kubectl describe -l'
alias kdn='kubectl describe --namespace'
alias kdno='kubectl describe nodes'
alias kdnol='kubectl describe nodes -l'
alias kdns='kubectl describe namespaces'
alias kdnsall='kubectl describe namespaces --all-namespaces'
alias kdnsl='kubectl describe namespaces -l'
alias kdpo='kubectl describe pods'
alias kdpoall='kubectl describe pods --all-namespaces'
alias kdpol='kubectl describe pods -l'
alias kdpon='kubectl describe pods --namespace'
alias kdsec='kubectl describe secret'
alias kdsecall='kubectl describe secret --all-namespaces'
alias kdsecl='kubectl describe secret -l'
alias kdsecn='kubectl describe secret --namespace'
alias kdsvc='kubectl describe service'
alias kdsvcall='kubectl describe service --all-namespaces'
alias kdsvcl='kubectl describe service -l'
alias kdsvcn='kubectl describe service --namespace'

alias kex='kubectl exec -i -t'
alias kexn='kubectl exec -i -t --namespace'

alias kg='kubectl get'
alias kgall='kubectl get --all-namespaces'
alias kgallojson='kubectl get --all-namespaces -o=json'
alias kgallowide='kubectl get --all-namespaces -o=wide'
alias kgallowidesl='kubectl get --all-namespaces -o=wide --show-labels'
alias kgalloyaml='kubectl get --all-namespaces -o=yaml'
alias kgallsl='kubectl get --all-namespaces --show-labels'
alias kgallslowide='kubectl get --all-namespaces --show-labels -o=wide'
alias kgallslw='kubectl get --all-namespaces --show-labels --watch'
alias kgallslwowide='kubectl get --all-namespaces --show-labels --watch -o=wide'
alias kgallw='kubectl get --all-namespaces --watch'
alias kgallwojson='kubectl get --all-namespaces --watch -o=json'
alias kgallwowide='kubectl get --all-namespaces --watch -o=wide'
alias kgallwowidesl='kubectl get --all-namespaces --watch -o=wide --show-labels'
alias kgallwoyaml='kubectl get --all-namespaces --watch -o=yaml'
alias kgallwsl='kubectl get --all-namespaces --watch --show-labels'
alias kgallwslowide='kubectl get --all-namespaces --watch --show-labels -o=wide'
alias kgcm='kubectl get configmap'
alias kgcmall='kubectl get configmap --all-namespaces'
alias kgcmallojson='kubectl get configmap --all-namespaces -o=json'
alias kgcmallowide='kubectl get configmap --all-namespaces -o=wide'
alias kgcmalloyaml='kubectl get configmap --all-namespaces -o=yaml'
alias kgcmallw='kubectl get configmap --all-namespaces --watch'
alias kgcmallwojson='kubectl get configmap --all-namespaces --watch -o=json'
alias kgcmallwowide='kubectl get configmap --all-namespaces --watch -o=wide'
alias kgcmallwoyaml='kubectl get configmap --all-namespaces --watch -o=yaml'
alias kgcml='kubectl get configmap -l'
alias kgcmn='kubectl get configmap --namespace'
alias kgcmojson='kubectl get configmap -o=json'
alias kgcmojsonall='kubectl get configmap -o=json --all-namespaces'
alias kgcmojsonl='kubectl get configmap -o=json -l'
alias kgcmojsonn='kubectl get configmap -o=json --namespace'
alias kgcmowide='kubectl get configmap -o=wide'
alias kgcmowideall='kubectl get configmap -o=wide --all-namespaces'
alias kgcmowidel='kubectl get configmap -o=wide -l'
alias kgcmowiden='kubectl get configmap -o=wide --namespace'
alias kgcmoyaml='kubectl get configmap -o=yaml'
alias kgcmoyamlall='kubectl get configmap -o=yaml --all-namespaces'
alias kgcmoyamll='kubectl get configmap -o=yaml -l'
alias kgcmoyamln='kubectl get configmap -o=yaml --namespace'
alias kgcmw='kubectl get configmap --watch'
alias kgcmwall='kubectl get configmap --watch --all-namespaces'
alias kgcmwallojson='kubectl get configmap --watch --all-namespaces -o=json'
alias kgcmwallowide='kubectl get configmap --watch --all-namespaces -o=wide'
alias kgcmwalloyaml='kubectl get configmap --watch --all-namespaces -o=yaml'
alias kgcmwl='kubectl get configmap --watch -l'
alias kgcmwn='kubectl get configmap --watch --namespace'
alias kgcmwojson='kubectl get configmap --watch -o=json'
alias kgcmwojsonall='kubectl get configmap --watch -o=json --all-namespaces'
alias kgcmwojsonl='kubectl get configmap --watch -o=json -l'
alias kgcmwojsonn='kubectl get configmap --watch -o=json --namespace'
alias kgcmwowide='kubectl get configmap --watch -o=wide'
alias kgcmwowideall='kubectl get configmap --watch -o=wide --all-namespaces'
alias kgcmwowidel='kubectl get configmap --watch -o=wide -l'
alias kgcmwowiden='kubectl get configmap --watch -o=wide --namespace'
alias kgcmwoyaml='kubectl get configmap --watch -o=yaml'
alias kgcmwoyamlall='kubectl get configmap --watch -o=yaml --all-namespaces'
alias kgcmwoyamll='kubectl get configmap --watch -o=yaml -l'
alias kgcmwoyamln='kubectl get configmap --watch -o=yaml --namespace'
alias kgdep='kubectl get deployment'
alias kgdepall='kubectl get deployment --all-namespaces'
alias kgdepallojson='kubectl get deployment --all-namespaces -o=json'
alias kgdepallowide='kubectl get deployment --all-namespaces -o=wide'
alias kgdepallowidesl='kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgdepalloyaml='kubectl get deployment --all-namespaces -o=yaml'
alias kgdepallsl='kubectl get deployment --all-namespaces --show-labels'
alias kgdepallslowide='kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgdepallslw='kubectl get deployment --all-namespaces --show-labels --watch'
alias kgdepallslwowide='kubectl get deployment --all-namespaces --show-labels --watch -o=wide'
alias kgdepallw='kubectl get deployment --all-namespaces --watch'
alias kgdepallwojson='kubectl get deployment --all-namespaces --watch -o=json'
alias kgdepallwowide='kubectl get deployment --all-namespaces --watch -o=wide'
alias kgdepallwowidesl='kubectl get deployment --all-namespaces --watch -o=wide --show-labels'
alias kgdepallwoyaml='kubectl get deployment --all-namespaces --watch -o=yaml'
alias kgdepallwsl='kubectl get deployment --all-namespaces --watch --show-labels'
alias kgdepallwslowide='kubectl get deployment --all-namespaces --watch --show-labels -o=wide'
alias kgdepl='kubectl get deployment -l'
alias kgdepn='kubectl get deployment --namespace'
alias kgdepojson='kubectl get deployment -o=json'
alias kgdepojsonall='kubectl get deployment -o=json --all-namespaces'
alias kgdepojsonl='kubectl get deployment -o=json -l'
alias kgdepojsonn='kubectl get deployment -o=json --namespace'
alias kgdepowide='kubectl get deployment -o=wide'
alias kgdepowideall='kubectl get deployment -o=wide --all-namespaces'
alias kgdepowideallsl='kubectl get deployment -o=wide --all-namespaces --show-labels'
alias kgdepowidel='kubectl get deployment -o=wide -l'
alias kgdepowiden='kubectl get deployment -o=wide --namespace'
alias kgdepowidesl='kubectl get deployment -o=wide --show-labels'
alias kgdepowideslall='kubectl get deployment -o=wide --show-labels --all-namespaces'
alias kgdepowidesll='kubectl get deployment -o=wide --show-labels -l'
alias kgdepowidesln='kubectl get deployment -o=wide --show-labels --namespace'
alias kgdepoyaml='kubectl get deployment -o=yaml'
alias kgdepoyamlall='kubectl get deployment -o=yaml --all-namespaces'
alias kgdepoyamll='kubectl get deployment -o=yaml -l'
alias kgdepoyamln='kubectl get deployment -o=yaml --namespace'
alias kgdepsl='kubectl get deployment --show-labels'
alias kgdepslall='kubectl get deployment --show-labels --all-namespaces'
alias kgdepslallowide='kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgdepslallw='kubectl get deployment --show-labels --all-namespaces --watch'
alias kgdepslallwowide='kubectl get deployment --show-labels --all-namespaces --watch -o=wide'
alias kgdepsll='kubectl get deployment --show-labels -l'
alias kgdepsln='kubectl get deployment --show-labels --namespace'
alias kgdepslowide='kubectl get deployment --show-labels -o=wide'
alias kgdepslowideall='kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgdepslowidel='kubectl get deployment --show-labels -o=wide -l'
alias kgdepslowiden='kubectl get deployment --show-labels -o=wide --namespace'
alias kgdepslw='kubectl get deployment --show-labels --watch'
alias kgdepslwall='kubectl get deployment --show-labels --watch --all-namespaces'
alias kgdepslwallowide='kubectl get deployment --show-labels --watch --all-namespaces -o=wide'
alias kgdepslwl='kubectl get deployment --show-labels --watch -l'
alias kgdepslwn='kubectl get deployment --show-labels --watch --namespace'
alias kgdepslwowide='kubectl get deployment --show-labels --watch -o=wide'
alias kgdepslwowideall='kubectl get deployment --show-labels --watch -o=wide --all-namespaces'
alias kgdepslwowidel='kubectl get deployment --show-labels --watch -o=wide -l'
alias kgdepslwowiden='kubectl get deployment --show-labels --watch -o=wide --namespace'
alias kgdepw='kubectl get deployment --watch'
alias kgdepwall='kubectl get deployment --watch --all-namespaces'
alias kgdepwallojson='kubectl get deployment --watch --all-namespaces -o=json'
alias kgdepwallowide='kubectl get deployment --watch --all-namespaces -o=wide'
alias kgdepwallowidesl='kubectl get deployment --watch --all-namespaces -o=wide --show-labels'
alias kgdepwalloyaml='kubectl get deployment --watch --all-namespaces -o=yaml'
alias kgdepwallsl='kubectl get deployment --watch --all-namespaces --show-labels'
alias kgdepwallslowide='kubectl get deployment --watch --all-namespaces --show-labels -o=wide'
alias kgdepwl='kubectl get deployment --watch -l'
alias kgdepwn='kubectl get deployment --watch --namespace'
alias kgdepwojson='kubectl get deployment --watch -o=json'
alias kgdepwojsonall='kubectl get deployment --watch -o=json --all-namespaces'
alias kgdepwojsonl='kubectl get deployment --watch -o=json -l'
alias kgdepwojsonn='kubectl get deployment --watch -o=json --namespace'
alias kgdepwowide='kubectl get deployment --watch -o=wide'
alias kgdepwowideall='kubectl get deployment --watch -o=wide --all-namespaces'
alias kgdepwowideallsl='kubectl get deployment --watch -o=wide --all-namespaces --show-labels'
alias kgdepwowidel='kubectl get deployment --watch -o=wide -l'
alias kgdepwowiden='kubectl get deployment --watch -o=wide --namespace'
alias kgdepwowidesl='kubectl get deployment --watch -o=wide --show-labels'
alias kgdepwowideslall='kubectl get deployment --watch -o=wide --show-labels --all-namespaces'
alias kgdepwowidesll='kubectl get deployment --watch -o=wide --show-labels -l'
alias kgdepwowidesln='kubectl get deployment --watch -o=wide --show-labels --namespace'
alias kgdepwoyaml='kubectl get deployment --watch -o=yaml'
alias kgdepwoyamlall='kubectl get deployment --watch -o=yaml --all-namespaces'
alias kgdepwoyamll='kubectl get deployment --watch -o=yaml -l'
alias kgdepwoyamln='kubectl get deployment --watch -o=yaml --namespace'
alias kgdepwsl='kubectl get deployment --watch --show-labels'
alias kgdepwslall='kubectl get deployment --watch --show-labels --all-namespaces'
alias kgdepwslallowide='kubectl get deployment --watch --show-labels --all-namespaces -o=wide'
alias kgdepwsll='kubectl get deployment --watch --show-labels -l'
alias kgdepwsln='kubectl get deployment --watch --show-labels --namespace'
alias kgdepwslowide='kubectl get deployment --watch --show-labels -o=wide'
alias kgdepwslowideall='kubectl get deployment --watch --show-labels -o=wide --all-namespaces'
alias kgdepwslowidel='kubectl get deployment --watch --show-labels -o=wide -l'
alias kgdepwslowiden='kubectl get deployment --watch --show-labels -o=wide --namespace'
alias kgf='kubectl get --recursive -f'
alias kging='kubectl get ingress'
alias kgingall='kubectl get ingress --all-namespaces'
alias kgingallojson='kubectl get ingress --all-namespaces -o=json'
alias kgingallowide='kubectl get ingress --all-namespaces -o=wide'
alias kgingalloyaml='kubectl get ingress --all-namespaces -o=yaml'
alias kgingallw='kubectl get ingress --all-namespaces --watch'
alias kgingallwojson='kubectl get ingress --all-namespaces --watch -o=json'
alias kgingallwowide='kubectl get ingress --all-namespaces --watch -o=wide'
alias kgingallwoyaml='kubectl get ingress --all-namespaces --watch -o=yaml'
alias kgingl='kubectl get ingress -l'
alias kgingn='kubectl get ingress --namespace'
alias kgingojson='kubectl get ingress -o=json'
alias kgingojsonall='kubectl get ingress -o=json --all-namespaces'
alias kgingojsonl='kubectl get ingress -o=json -l'
alias kgingojsonn='kubectl get ingress -o=json --namespace'
alias kgingowide='kubectl get ingress -o=wide'
alias kgingowideall='kubectl get ingress -o=wide --all-namespaces'
alias kgingowidel='kubectl get ingress -o=wide -l'
alias kgingowiden='kubectl get ingress -o=wide --namespace'
alias kgingoyaml='kubectl get ingress -o=yaml'
alias kgingoyamlall='kubectl get ingress -o=yaml --all-namespaces'
alias kgingoyamll='kubectl get ingress -o=yaml -l'
alias kgingoyamln='kubectl get ingress -o=yaml --namespace'
alias kgingw='kubectl get ingress --watch'
alias kgingwall='kubectl get ingress --watch --all-namespaces'
alias kgingwallojson='kubectl get ingress --watch --all-namespaces -o=json'
alias kgingwallowide='kubectl get ingress --watch --all-namespaces -o=wide'
alias kgingwalloyaml='kubectl get ingress --watch --all-namespaces -o=yaml'
alias kgingwl='kubectl get ingress --watch -l'
alias kgingwn='kubectl get ingress --watch --namespace'
alias kgingwojson='kubectl get ingress --watch -o=json'
alias kgingwojsonall='kubectl get ingress --watch -o=json --all-namespaces'
alias kgingwojsonl='kubectl get ingress --watch -o=json -l'
alias kgingwojsonn='kubectl get ingress --watch -o=json --namespace'
alias kgingwowide='kubectl get ingress --watch -o=wide'
alias kgingwowideall='kubectl get ingress --watch -o=wide --all-namespaces'
alias kgingwowidel='kubectl get ingress --watch -o=wide -l'
alias kgingwowiden='kubectl get ingress --watch -o=wide --namespace'
alias kgingwoyaml='kubectl get ingress --watch -o=yaml'
alias kgingwoyamlall='kubectl get ingress --watch -o=yaml --all-namespaces'
alias kgingwoyamll='kubectl get ingress --watch -o=yaml -l'
alias kgingwoyamln='kubectl get ingress --watch -o=yaml --namespace'
alias kgl='kubectl get -l'
alias kgn='kubectl get --namespace'
alias kgno='kubectl get nodes'
alias kgnol='kubectl get nodes -l'
alias kgnoojson='kubectl get nodes -o=json'
alias kgnoojsonl='kubectl get nodes -o=json -l'
alias kgnoowide='kubectl get nodes -o=wide'
alias kgnoowidel='kubectl get nodes -o=wide -l'
alias kgnooyaml='kubectl get nodes -o=yaml'
alias kgnooyamll='kubectl get nodes -o=yaml -l'
alias kgnow='kubectl get nodes --watch'
alias kgnowl='kubectl get nodes --watch -l'
alias kgnowojson='kubectl get nodes --watch -o=json'
alias kgnowojsonl='kubectl get nodes --watch -o=json -l'
alias kgnowowide='kubectl get nodes --watch -o=wide'
alias kgnowowidel='kubectl get nodes --watch -o=wide -l'
alias kgnowoyaml='kubectl get nodes --watch -o=yaml'
alias kgnowoyamll='kubectl get nodes --watch -o=yaml -l'
alias kgns='kubectl get namespaces'
alias kgnsall='kubectl get namespaces --all-namespaces'
alias kgnsallojson='kubectl get namespaces --all-namespaces -o=json'
alias kgnsallowide='kubectl get namespaces --all-namespaces -o=wide'
alias kgnsalloyaml='kubectl get namespaces --all-namespaces -o=yaml'
alias kgnsallw='kubectl get namespaces --all-namespaces --watch'
alias kgnsallwojson='kubectl get namespaces --all-namespaces --watch -o=json'
alias kgnsallwowide='kubectl get namespaces --all-namespaces --watch -o=wide'
alias kgnsallwoyaml='kubectl get namespaces --all-namespaces --watch -o=yaml'
alias kgnsl='kubectl get namespaces -l'
alias kgnsojson='kubectl get namespaces -o=json'
alias kgnsojsonall='kubectl get namespaces -o=json --all-namespaces'
alias kgnsojsonl='kubectl get namespaces -o=json -l'
alias kgnsowide='kubectl get namespaces -o=wide'
alias kgnsowideall='kubectl get namespaces -o=wide --all-namespaces'
alias kgnsowidel='kubectl get namespaces -o=wide -l'
alias kgnsoyaml='kubectl get namespaces -o=yaml'
alias kgnsoyamlall='kubectl get namespaces -o=yaml --all-namespaces'
alias kgnsoyamll='kubectl get namespaces -o=yaml -l'
alias kgnsw='kubectl get namespaces --watch'
alias kgnswall='kubectl get namespaces --watch --all-namespaces'
alias kgnswallojson='kubectl get namespaces --watch --all-namespaces -o=json'
alias kgnswallowide='kubectl get namespaces --watch --all-namespaces -o=wide'
alias kgnswalloyaml='kubectl get namespaces --watch --all-namespaces -o=yaml'
alias kgnswl='kubectl get namespaces --watch -l'
alias kgnswojson='kubectl get namespaces --watch -o=json'
alias kgnswojsonall='kubectl get namespaces --watch -o=json --all-namespaces'
alias kgnswojsonl='kubectl get namespaces --watch -o=json -l'
alias kgnswowide='kubectl get namespaces --watch -o=wide'
alias kgnswowideall='kubectl get namespaces --watch -o=wide --all-namespaces'
alias kgnswowidel='kubectl get namespaces --watch -o=wide -l'
alias kgnswoyaml='kubectl get namespaces --watch -o=yaml'
alias kgnswoyamlall='kubectl get namespaces --watch -o=yaml --all-namespaces'
alias kgnswoyamll='kubectl get namespaces --watch -o=yaml -l'
alias kgojson='kubectl get -o=json'
alias kgojsonall='kubectl get -o=json --all-namespaces'
alias kgojsonf='kubectl get -o=json --recursive -f'
alias kgojsonl='kubectl get -o=json -l'
alias kgojsonn='kubectl get -o=json --namespace'
alias kgowide='kubectl get -o=wide'
alias kgowideall='kubectl get -o=wide --all-namespaces'
alias kgowideallsl='kubectl get -o=wide --all-namespaces --show-labels'
alias kgowidef='kubectl get -o=wide --recursive -f'
alias kgowidel='kubectl get -o=wide -l'
alias kgowiden='kubectl get -o=wide --namespace'
alias kgowidesl='kubectl get -o=wide --show-labels'
alias kgowideslall='kubectl get -o=wide --show-labels --all-namespaces'
alias kgowideslf='kubectl get -o=wide --show-labels --recursive -f'
alias kgowidesll='kubectl get -o=wide --show-labels -l'
alias kgowidesln='kubectl get -o=wide --show-labels --namespace'
alias kgoyaml='kubectl get -o=yaml'
alias kgoyamlall='kubectl get -o=yaml --all-namespaces'
alias kgoyamlf='kubectl get -o=yaml --recursive -f'
alias kgoyamll='kubectl get -o=yaml -l'
alias kgoyamln='kubectl get -o=yaml --namespace'
alias kgpo='kubectl get pods'
alias kgpoall='kubectl get pods --all-namespaces'
alias kgpoallojson='kubectl get pods --all-namespaces -o=json'
alias kgpoallowide='kubectl get pods --all-namespaces -o=wide'
alias kgpoallowidesl='kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgpoalloyaml='kubectl get pods --all-namespaces -o=yaml'
alias kgpoallsl='kubectl get pods --all-namespaces --show-labels'
alias kgpoallslowide='kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgpoallslw='kubectl get pods --all-namespaces --show-labels --watch'
alias kgpoallslwowide='kubectl get pods --all-namespaces --show-labels --watch -o=wide'
alias kgpoallw='kubectl get pods --all-namespaces --watch'
alias kgpoallwojson='kubectl get pods --all-namespaces --watch -o=json'
alias kgpoallwowide='kubectl get pods --all-namespaces --watch -o=wide'
alias kgpoallwowidesl='kubectl get pods --all-namespaces --watch -o=wide --show-labels'
alias kgpoallwoyaml='kubectl get pods --all-namespaces --watch -o=yaml'
alias kgpoallwsl='kubectl get pods --all-namespaces --watch --show-labels'
alias kgpoallwslowide='kubectl get pods --all-namespaces --watch --show-labels -o=wide'
alias kgpol='kubectl get pods -l'
alias kgpon='kubectl get pods --namespace'
alias kgpoojson='kubectl get pods -o=json'
alias kgpoojsonall='kubectl get pods -o=json --all-namespaces'
alias kgpoojsonl='kubectl get pods -o=json -l'
alias kgpoojsonn='kubectl get pods -o=json --namespace'
alias kgpoowide='kubectl get pods -o=wide'
alias kgpoowideall='kubectl get pods -o=wide --all-namespaces'
alias kgpoowideallsl='kubectl get pods -o=wide --all-namespaces --show-labels'
alias kgpoowidel='kubectl get pods -o=wide -l'
alias kgpoowiden='kubectl get pods -o=wide --namespace'
alias kgpoowidesl='kubectl get pods -o=wide --show-labels'
alias kgpoowideslall='kubectl get pods -o=wide --show-labels --all-namespaces'
alias kgpoowidesll='kubectl get pods -o=wide --show-labels -l'
alias kgpoowidesln='kubectl get pods -o=wide --show-labels --namespace'
alias kgpooyaml='kubectl get pods -o=yaml'
alias kgpooyamlall='kubectl get pods -o=yaml --all-namespaces'
alias kgpooyamll='kubectl get pods -o=yaml -l'
alias kgpooyamln='kubectl get pods -o=yaml --namespace'
alias kgposl='kubectl get pods --show-labels'
alias kgposlall='kubectl get pods --show-labels --all-namespaces'
alias kgposlallowide='kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgposlallw='kubectl get pods --show-labels --all-namespaces --watch'
alias kgposlallwowide='kubectl get pods --show-labels --all-namespaces --watch -o=wide'
alias kgposll='kubectl get pods --show-labels -l'
alias kgposln='kubectl get pods --show-labels --namespace'
alias kgposlowide='kubectl get pods --show-labels -o=wide'
alias kgposlowideall='kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgposlowidel='kubectl get pods --show-labels -o=wide -l'
alias kgposlowiden='kubectl get pods --show-labels -o=wide --namespace'
alias kgposlw='kubectl get pods --show-labels --watch'
alias kgposlwall='kubectl get pods --show-labels --watch --all-namespaces'
alias kgposlwallowide='kubectl get pods --show-labels --watch --all-namespaces -o=wide'
alias kgposlwl='kubectl get pods --show-labels --watch -l'
alias kgposlwn='kubectl get pods --show-labels --watch --namespace'
alias kgposlwowide='kubectl get pods --show-labels --watch -o=wide'
alias kgposlwowideall='kubectl get pods --show-labels --watch -o=wide --all-namespaces'
alias kgposlwowidel='kubectl get pods --show-labels --watch -o=wide -l'
alias kgposlwowiden='kubectl get pods --show-labels --watch -o=wide --namespace'
alias kgpow='kubectl get pods --watch'
alias kgpowall='kubectl get pods --watch --all-namespaces'
alias kgpowallojson='kubectl get pods --watch --all-namespaces -o=json'
alias kgpowallowide='kubectl get pods --watch --all-namespaces -o=wide'
alias kgpowallowidesl='kubectl get pods --watch --all-namespaces -o=wide --show-labels'
alias kgpowalloyaml='kubectl get pods --watch --all-namespaces -o=yaml'
alias kgpowallsl='kubectl get pods --watch --all-namespaces --show-labels'
alias kgpowallslowide='kubectl get pods --watch --all-namespaces --show-labels -o=wide'
alias kgpowl='kubectl get pods --watch -l'
alias kgpown='kubectl get pods --watch --namespace'
alias kgpowojson='kubectl get pods --watch -o=json'
alias kgpowojsonall='kubectl get pods --watch -o=json --all-namespaces'
alias kgpowojsonl='kubectl get pods --watch -o=json -l'
alias kgpowojsonn='kubectl get pods --watch -o=json --namespace'
alias kgpowowide='kubectl get pods --watch -o=wide'
alias kgpowowideall='kubectl get pods --watch -o=wide --all-namespaces'
alias kgpowowideallsl='kubectl get pods --watch -o=wide --all-namespaces --show-labels'
alias kgpowowidel='kubectl get pods --watch -o=wide -l'
alias kgpowowiden='kubectl get pods --watch -o=wide --namespace'
alias kgpowowidesl='kubectl get pods --watch -o=wide --show-labels'
alias kgpowowideslall='kubectl get pods --watch -o=wide --show-labels --all-namespaces'
alias kgpowowidesll='kubectl get pods --watch -o=wide --show-labels -l'
alias kgpowowidesln='kubectl get pods --watch -o=wide --show-labels --namespace'
alias kgpowoyaml='kubectl get pods --watch -o=yaml'
alias kgpowoyamlall='kubectl get pods --watch -o=yaml --all-namespaces'
alias kgpowoyamll='kubectl get pods --watch -o=yaml -l'
alias kgpowoyamln='kubectl get pods --watch -o=yaml --namespace'
alias kgpowsl='kubectl get pods --watch --show-labels'
alias kgpowslall='kubectl get pods --watch --show-labels --all-namespaces'
alias kgpowslallowide='kubectl get pods --watch --show-labels --all-namespaces -o=wide'
alias kgpowsll='kubectl get pods --watch --show-labels -l'
alias kgpowsln='kubectl get pods --watch --show-labels --namespace'
alias kgpowslowide='kubectl get pods --watch --show-labels -o=wide'
alias kgpowslowideall='kubectl get pods --watch --show-labels -o=wide --all-namespaces'
alias kgpowslowidel='kubectl get pods --watch --show-labels -o=wide -l'
alias kgpowslowiden='kubectl get pods --watch --show-labels -o=wide --namespace'
alias kgsec='kubectl get secret'
alias kgsecall='kubectl get secret --all-namespaces'
alias kgsecallojson='kubectl get secret --all-namespaces -o=json'
alias kgsecallowide='kubectl get secret --all-namespaces -o=wide'
alias kgsecalloyaml='kubectl get secret --all-namespaces -o=yaml'
alias kgsecallw='kubectl get secret --all-namespaces --watch'
alias kgsecallwojson='kubectl get secret --all-namespaces --watch -o=json'
alias kgsecallwowide='kubectl get secret --all-namespaces --watch -o=wide'
alias kgsecallwoyaml='kubectl get secret --all-namespaces --watch -o=yaml'
alias kgsecl='kubectl get secret -l'
alias kgsecn='kubectl get secret --namespace'
alias kgsecojson='kubectl get secret -o=json'
alias kgsecojsonall='kubectl get secret -o=json --all-namespaces'
alias kgsecojsonl='kubectl get secret -o=json -l'
alias kgsecojsonn='kubectl get secret -o=json --namespace'
alias kgsecowide='kubectl get secret -o=wide'
alias kgsecowideall='kubectl get secret -o=wide --all-namespaces'
alias kgsecowidel='kubectl get secret -o=wide -l'
alias kgsecowiden='kubectl get secret -o=wide --namespace'
alias kgsecoyaml='kubectl get secret -o=yaml'
alias kgsecoyamlall='kubectl get secret -o=yaml --all-namespaces'
alias kgsecoyamll='kubectl get secret -o=yaml -l'
alias kgsecoyamln='kubectl get secret -o=yaml --namespace'
alias kgsecw='kubectl get secret --watch'
alias kgsecwall='kubectl get secret --watch --all-namespaces'
alias kgsecwallojson='kubectl get secret --watch --all-namespaces -o=json'
alias kgsecwallowide='kubectl get secret --watch --all-namespaces -o=wide'
alias kgsecwalloyaml='kubectl get secret --watch --all-namespaces -o=yaml'
alias kgsecwl='kubectl get secret --watch -l'
alias kgsecwn='kubectl get secret --watch --namespace'
alias kgsecwojson='kubectl get secret --watch -o=json'
alias kgsecwojsonall='kubectl get secret --watch -o=json --all-namespaces'
alias kgsecwojsonl='kubectl get secret --watch -o=json -l'
alias kgsecwojsonn='kubectl get secret --watch -o=json --namespace'
alias kgsecwowide='kubectl get secret --watch -o=wide'
alias kgsecwowideall='kubectl get secret --watch -o=wide --all-namespaces'
alias kgsecwowidel='kubectl get secret --watch -o=wide -l'
alias kgsecwowiden='kubectl get secret --watch -o=wide --namespace'
alias kgsecwoyaml='kubectl get secret --watch -o=yaml'
alias kgsecwoyamlall='kubectl get secret --watch -o=yaml --all-namespaces'
alias kgsecwoyamll='kubectl get secret --watch -o=yaml -l'
alias kgsecwoyamln='kubectl get secret --watch -o=yaml --namespace'
alias kgsl='kubectl get --show-labels'
alias kgslall='kubectl get --show-labels --all-namespaces'
alias kgslallowide='kubectl get --show-labels --all-namespaces -o=wide'
alias kgslallw='kubectl get --show-labels --all-namespaces --watch'
alias kgslallwowide='kubectl get --show-labels --all-namespaces --watch -o=wide'
alias kgslf='kubectl get --show-labels --recursive -f'
alias kgsll='kubectl get --show-labels -l'
alias kgsln='kubectl get --show-labels --namespace'
alias kgslowide='kubectl get --show-labels -o=wide'
alias kgslowideall='kubectl get --show-labels -o=wide --all-namespaces'
alias kgslowidef='kubectl get --show-labels -o=wide --recursive -f'
alias kgslowidel='kubectl get --show-labels -o=wide -l'
alias kgslowiden='kubectl get --show-labels -o=wide --namespace'
alias kgslw='kubectl get --show-labels --watch'
alias kgslwall='kubectl get --show-labels --watch --all-namespaces'
alias kgslwallowide='kubectl get --show-labels --watch --all-namespaces -o=wide'
alias kgslwf='kubectl get --show-labels --watch --recursive -f'
alias kgslwl='kubectl get --show-labels --watch -l'
alias kgslwn='kubectl get --show-labels --watch --namespace'
alias kgslwowide='kubectl get --show-labels --watch -o=wide'
alias kgslwowideall='kubectl get --show-labels --watch -o=wide --all-namespaces'
alias kgslwowidef='kubectl get --show-labels --watch -o=wide --recursive -f'
alias kgslwowidel='kubectl get --show-labels --watch -o=wide -l'
alias kgslwowiden='kubectl get --show-labels --watch -o=wide --namespace'
alias kgsvc='kubectl get service'
alias kgsvcall='kubectl get service --all-namespaces'
alias kgsvcallojson='kubectl get service --all-namespaces -o=json'
alias kgsvcallowide='kubectl get service --all-namespaces -o=wide'
alias kgsvcalloyaml='kubectl get service --all-namespaces -o=yaml'
alias kgsvcallw='kubectl get service --all-namespaces --watch'
alias kgsvcallwojson='kubectl get service --all-namespaces --watch -o=json'
alias kgsvcallwowide='kubectl get service --all-namespaces --watch -o=wide'
alias kgsvcallwoyaml='kubectl get service --all-namespaces --watch -o=yaml'
alias kgsvcl='kubectl get service -l'
alias kgsvcn='kubectl get service --namespace'
alias kgsvcojson='kubectl get service -o=json'
alias kgsvcojsonall='kubectl get service -o=json --all-namespaces'
alias kgsvcojsonl='kubectl get service -o=json -l'
alias kgsvcojsonn='kubectl get service -o=json --namespace'
alias kgsvcowide='kubectl get service -o=wide'
alias kgsvcowideall='kubectl get service -o=wide --all-namespaces'
alias kgsvcowidel='kubectl get service -o=wide -l'
alias kgsvcowiden='kubectl get service -o=wide --namespace'
alias kgsvcoyaml='kubectl get service -o=yaml'
alias kgsvcoyamlall='kubectl get service -o=yaml --all-namespaces'
alias kgsvcoyamll='kubectl get service -o=yaml -l'
alias kgsvcoyamln='kubectl get service -o=yaml --namespace'
alias kgsvcw='kubectl get service --watch'
alias kgsvcwall='kubectl get service --watch --all-namespaces'
alias kgsvcwallojson='kubectl get service --watch --all-namespaces -o=json'
alias kgsvcwallowide='kubectl get service --watch --all-namespaces -o=wide'
alias kgsvcwalloyaml='kubectl get service --watch --all-namespaces -o=yaml'
alias kgsvcwl='kubectl get service --watch -l'
alias kgsvcwn='kubectl get service --watch --namespace'
alias kgsvcwojson='kubectl get service --watch -o=json'
alias kgsvcwojsonall='kubectl get service --watch -o=json --all-namespaces'
alias kgsvcwojsonl='kubectl get service --watch -o=json -l'
alias kgsvcwojsonn='kubectl get service --watch -o=json --namespace'
alias kgsvcwowide='kubectl get service --watch -o=wide'
alias kgsvcwowideall='kubectl get service --watch -o=wide --all-namespaces'
alias kgsvcwowidel='kubectl get service --watch -o=wide -l'
alias kgsvcwowiden='kubectl get service --watch -o=wide --namespace'
alias kgsvcwoyaml='kubectl get service --watch -o=yaml'
alias kgsvcwoyamlall='kubectl get service --watch -o=yaml --all-namespaces'
alias kgsvcwoyamll='kubectl get service --watch -o=yaml -l'
alias kgsvcwoyamln='kubectl get service --watch -o=yaml --namespace'
alias kgw='kubectl get --watch'
alias kgwall='kubectl get --watch --all-namespaces'
alias kgwallojson='kubectl get --watch --all-namespaces -o=json'
alias kgwallowide='kubectl get --watch --all-namespaces -o=wide'
alias kgwallowidesl='kubectl get --watch --all-namespaces -o=wide --show-labels'
alias kgwalloyaml='kubectl get --watch --all-namespaces -o=yaml'
alias kgwallsl='kubectl get --watch --all-namespaces --show-labels'
alias kgwallslowide='kubectl get --watch --all-namespaces --show-labels -o=wide'
alias kgwf='kubectl get --watch --recursive -f'
alias kgwl='kubectl get --watch -l'
alias kgwn='kubectl get --watch --namespace'
alias kgwojson='kubectl get --watch -o=json'
alias kgwojsonall='kubectl get --watch -o=json --all-namespaces'
alias kgwojsonf='kubectl get --watch -o=json --recursive -f'
alias kgwojsonl='kubectl get --watch -o=json -l'
alias kgwojsonn='kubectl get --watch -o=json --namespace'
alias kgwowide='kubectl get --watch -o=wide'
alias kgwowideall='kubectl get --watch -o=wide --all-namespaces'
alias kgwowideallsl='kubectl get --watch -o=wide --all-namespaces --show-labels'
alias kgwowidef='kubectl get --watch -o=wide --recursive -f'
alias kgwowidel='kubectl get --watch -o=wide -l'
alias kgwowiden='kubectl get --watch -o=wide --namespace'
alias kgwowidesl='kubectl get --watch -o=wide --show-labels'
alias kgwowideslall='kubectl get --watch -o=wide --show-labels --all-namespaces'
alias kgwowideslf='kubectl get --watch -o=wide --show-labels --recursive -f'
alias kgwowidesll='kubectl get --watch -o=wide --show-labels -l'
alias kgwowidesln='kubectl get --watch -o=wide --show-labels --namespace'
alias kgwoyaml='kubectl get --watch -o=yaml'
alias kgwoyamlall='kubectl get --watch -o=yaml --all-namespaces'
alias kgwoyamlf='kubectl get --watch -o=yaml --recursive -f'
alias kgwoyamll='kubectl get --watch -o=yaml -l'
alias kgwoyamln='kubectl get --watch -o=yaml --namespace'
alias kgwsl='kubectl get --watch --show-labels'
alias kgwslall='kubectl get --watch --show-labels --all-namespaces'
alias kgwslallowide='kubectl get --watch --show-labels --all-namespaces -o=wide'
alias kgwslf='kubectl get --watch --show-labels --recursive -f'
alias kgwsll='kubectl get --watch --show-labels -l'
alias kgwsln='kubectl get --watch --show-labels --namespace'
alias kgwslowide='kubectl get --watch --show-labels -o=wide'
alias kgwslowideall='kubectl get --watch --show-labels -o=wide --all-namespaces'
alias kgwslowidef='kubectl get --watch --show-labels -o=wide --recursive -f'
alias kgwslowidel='kubectl get --watch --show-labels -o=wide -l'
alias kgwslowiden='kubectl get --watch --show-labels -o=wide --namespace'

alias klo='kubectl logs -f'
alias klon='kubectl logs -f --namespace'
alias klop='kubectl logs -f -p'

alias kp='kubectl proxy'

alias krm='kubectl delete'
alias krmall='kubectl delete --all'
alias krmcm='kubectl delete configmap'
alias krmcmall='kubectl delete configmap --all'
alias krmcml='kubectl delete configmap -l'
alias krmcmn='kubectl delete configmap --namespace'
alias krmdep='kubectl delete deployment'
alias krmdepall='kubectl delete deployment --all'
alias krmdepl='kubectl delete deployment -l'
alias krmdepn='kubectl delete deployment --namespace'
alias krmf='kubectl delete --recursive -f'
alias krming='kubectl delete ingress'
alias krmingall='kubectl delete ingress --all'
alias krmingl='kubectl delete ingress -l'
alias krmingn='kubectl delete ingress --namespace'
alias krml='kubectl delete -l'
alias krmn='kubectl delete --namespace'
alias krmns='kubectl delete namespaces'
alias krmnsall='kubectl delete namespaces --all'
alias krmnsl='kubectl delete namespaces -l'
alias krmpo='kubectl delete pods'
alias krmpoall='kubectl delete pods --all'
alias krmpol='kubectl delete pods -l'
alias krmpon='kubectl delete pods --namespace'
alias krmsec='kubectl delete secret'
alias krmsecall='kubectl delete secret --all'
alias krmsecl='kubectl delete secret -l'
alias krmsecn='kubectl delete secret --namespace'
alias krmsvc='kubectl delete service'
alias krmsvcall='kubectl delete service --all'
alias krmsvcl='kubectl delete service -l'
alias krmsvcn='kubectl delete service --namespace'
alias krun='kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'

alias ksys='kubectl --namespace=kube-system'
alias ksysa='kubectl --namespace=kube-system apply --recursive -f'
alias ksysd='kubectl --namespace=kube-system describe'
alias ksysdcm='kubectl --namespace=kube-system describe configmap'
alias ksysdcml='kubectl --namespace=kube-system describe configmap -l'
alias ksysddep='kubectl --namespace=kube-system describe deployment'
alias ksysddepl='kubectl --namespace=kube-system describe deployment -l'
alias ksysding='kubectl --namespace=kube-system describe ingress'
alias ksysdingl='kubectl --namespace=kube-system describe ingress -l'
alias ksysdl='kubectl --namespace=kube-system describe -l'
alias ksysdpo='kubectl --namespace=kube-system describe pods'
alias ksysdpol='kubectl --namespace=kube-system describe pods -l'
alias ksysdsec='kubectl --namespace=kube-system describe secret'
alias ksysdsecl='kubectl --namespace=kube-system describe secret -l'
alias ksysdsvc='kubectl --namespace=kube-system describe service'
alias ksysdsvcl='kubectl --namespace=kube-system describe service -l'
alias ksysex='kubectl --namespace=kube-system exec -i -t'
alias ksysg='kubectl --namespace=kube-system get'
alias ksysgcm='kubectl --namespace=kube-system get configmap'
alias ksysgcml='kubectl --namespace=kube-system get configmap -l'
alias ksysgcmojson='kubectl --namespace=kube-system get configmap -o=json'
alias ksysgcmojsonl='kubectl --namespace=kube-system get configmap -o=json -l'
alias ksysgcmowide='kubectl --namespace=kube-system get configmap -o=wide'
alias ksysgcmowidel='kubectl --namespace=kube-system get configmap -o=wide -l'
alias ksysgcmoyaml='kubectl --namespace=kube-system get configmap -o=yaml'
alias ksysgcmoyamll='kubectl --namespace=kube-system get configmap -o=yaml -l'
alias ksysgcmw='kubectl --namespace=kube-system get configmap --watch'
alias ksysgcmwl='kubectl --namespace=kube-system get configmap --watch -l'
alias ksysgcmwojson='kubectl --namespace=kube-system get configmap --watch -o=json'
alias ksysgcmwojsonl='kubectl --namespace=kube-system get configmap --watch -o=json -l'
alias ksysgcmwowide='kubectl --namespace=kube-system get configmap --watch -o=wide'
alias ksysgcmwowidel='kubectl --namespace=kube-system get configmap --watch -o=wide -l'
alias ksysgcmwoyaml='kubectl --namespace=kube-system get configmap --watch -o=yaml'
alias ksysgcmwoyamll='kubectl --namespace=kube-system get configmap --watch -o=yaml -l'
alias ksysgdep='kubectl --namespace=kube-system get deployment'
alias ksysgdepl='kubectl --namespace=kube-system get deployment -l'
alias ksysgdepojson='kubectl --namespace=kube-system get deployment -o=json'
alias ksysgdepojsonl='kubectl --namespace=kube-system get deployment -o=json -l'
alias ksysgdepowide='kubectl --namespace=kube-system get deployment -o=wide'
alias ksysgdepowidel='kubectl --namespace=kube-system get deployment -o=wide -l'
alias ksysgdepowidesl='kubectl --namespace=kube-system get deployment -o=wide --show-labels'
alias ksysgdepowidesll='kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
alias ksysgdepoyaml='kubectl --namespace=kube-system get deployment -o=yaml'
alias ksysgdepoyamll='kubectl --namespace=kube-system get deployment -o=yaml -l'
alias ksysgdepsl='kubectl --namespace=kube-system get deployment --show-labels'
alias ksysgdepsll='kubectl --namespace=kube-system get deployment --show-labels -l'
alias ksysgdepslowide='kubectl --namespace=kube-system get deployment --show-labels -o=wide'
alias ksysgdepslowidel='kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
alias ksysgdepslw='kubectl --namespace=kube-system get deployment --show-labels --watch'
alias ksysgdepslwl='kubectl --namespace=kube-system get deployment --show-labels --watch -l'
alias ksysgdepslwowide='kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide'
alias ksysgdepslwowidel='kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide -l'
alias ksysgdepw='kubectl --namespace=kube-system get deployment --watch'
alias ksysgdepwl='kubectl --namespace=kube-system get deployment --watch -l'
alias ksysgdepwojson='kubectl --namespace=kube-system get deployment --watch -o=json'
alias ksysgdepwojsonl='kubectl --namespace=kube-system get deployment --watch -o=json -l'
alias ksysgdepwowide='kubectl --namespace=kube-system get deployment --watch -o=wide'
alias ksysgdepwowidel='kubectl --namespace=kube-system get deployment --watch -o=wide -l'
alias ksysgdepwowidesl='kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels'
alias ksysgdepwowidesll='kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels -l'
alias ksysgdepwoyaml='kubectl --namespace=kube-system get deployment --watch -o=yaml'
alias ksysgdepwoyamll='kubectl --namespace=kube-system get deployment --watch -o=yaml -l'
alias ksysgdepwsl='kubectl --namespace=kube-system get deployment --watch --show-labels'
alias ksysgdepwsll='kubectl --namespace=kube-system get deployment --watch --show-labels -l'
alias ksysgdepwslowide='kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide'
alias ksysgdepwslowidel='kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide -l'
alias ksysging='kubectl --namespace=kube-system get ingress'
alias ksysgingl='kubectl --namespace=kube-system get ingress -l'
alias ksysgingojson='kubectl --namespace=kube-system get ingress -o=json'
alias ksysgingojsonl='kubectl --namespace=kube-system get ingress -o=json -l'
alias ksysgingowide='kubectl --namespace=kube-system get ingress -o=wide'
alias ksysgingowidel='kubectl --namespace=kube-system get ingress -o=wide -l'
alias ksysgingoyaml='kubectl --namespace=kube-system get ingress -o=yaml'
alias ksysgingoyamll='kubectl --namespace=kube-system get ingress -o=yaml -l'
alias ksysgingw='kubectl --namespace=kube-system get ingress --watch'
alias ksysgingwl='kubectl --namespace=kube-system get ingress --watch -l'
alias ksysgingwojson='kubectl --namespace=kube-system get ingress --watch -o=json'
alias ksysgingwojsonl='kubectl --namespace=kube-system get ingress --watch -o=json -l'
alias ksysgingwowide='kubectl --namespace=kube-system get ingress --watch -o=wide'
alias ksysgingwowidel='kubectl --namespace=kube-system get ingress --watch -o=wide -l'
alias ksysgingwoyaml='kubectl --namespace=kube-system get ingress --watch -o=yaml'
alias ksysgingwoyamll='kubectl --namespace=kube-system get ingress --watch -o=yaml -l'
alias ksysgl='kubectl --namespace=kube-system get -l'
alias ksysgojson='kubectl --namespace=kube-system get -o=json'
alias ksysgojsonl='kubectl --namespace=kube-system get -o=json -l'
alias ksysgowide='kubectl --namespace=kube-system get -o=wide'
alias ksysgowidel='kubectl --namespace=kube-system get -o=wide -l'
alias ksysgowidesl='kubectl --namespace=kube-system get -o=wide --show-labels'
alias ksysgowidesll='kubectl --namespace=kube-system get -o=wide --show-labels -l'
alias ksysgoyaml='kubectl --namespace=kube-system get -o=yaml'
alias ksysgoyamll='kubectl --namespace=kube-system get -o=yaml -l'
alias ksysgpo='kubectl --namespace=kube-system get pods'
alias ksysgpol='kubectl --namespace=kube-system get pods -l'
alias ksysgpoojson='kubectl --namespace=kube-system get pods -o=json'
alias ksysgpoojsonl='kubectl --namespace=kube-system get pods -o=json -l'
alias ksysgpoowide='kubectl --namespace=kube-system get pods -o=wide'
alias ksysgpoowidel='kubectl --namespace=kube-system get pods -o=wide -l'
alias ksysgpoowidesl='kubectl --namespace=kube-system get pods -o=wide --show-labels'
alias ksysgpoowidesll='kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
alias ksysgpooyaml='kubectl --namespace=kube-system get pods -o=yaml'
alias ksysgpooyamll='kubectl --namespace=kube-system get pods -o=yaml -l'
alias ksysgposl='kubectl --namespace=kube-system get pods --show-labels'
alias ksysgposll='kubectl --namespace=kube-system get pods --show-labels -l'
alias ksysgposlowide='kubectl --namespace=kube-system get pods --show-labels -o=wide'
alias ksysgposlowidel='kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
alias ksysgposlw='kubectl --namespace=kube-system get pods --show-labels --watch'
alias ksysgposlwl='kubectl --namespace=kube-system get pods --show-labels --watch -l'
alias ksysgposlwowide='kubectl --namespace=kube-system get pods --show-labels --watch -o=wide'
alias ksysgposlwowidel='kubectl --namespace=kube-system get pods --show-labels --watch -o=wide -l'
alias ksysgpow='kubectl --namespace=kube-system get pods --watch'
alias ksysgpowl='kubectl --namespace=kube-system get pods --watch -l'
alias ksysgpowojson='kubectl --namespace=kube-system get pods --watch -o=json'
alias ksysgpowojsonl='kubectl --namespace=kube-system get pods --watch -o=json -l'
alias ksysgpowowide='kubectl --namespace=kube-system get pods --watch -o=wide'
alias ksysgpowowidel='kubectl --namespace=kube-system get pods --watch -o=wide -l'
alias ksysgpowowidesl='kubectl --namespace=kube-system get pods --watch -o=wide --show-labels'
alias ksysgpowowidesll='kubectl --namespace=kube-system get pods --watch -o=wide --show-labels -l'
alias ksysgpowoyaml='kubectl --namespace=kube-system get pods --watch -o=yaml'
alias ksysgpowoyamll='kubectl --namespace=kube-system get pods --watch -o=yaml -l'
alias ksysgpowsl='kubectl --namespace=kube-system get pods --watch --show-labels'
alias ksysgpowsll='kubectl --namespace=kube-system get pods --watch --show-labels -l'
alias ksysgpowslowide='kubectl --namespace=kube-system get pods --watch --show-labels -o=wide'
alias ksysgpowslowidel='kubectl --namespace=kube-system get pods --watch --show-labels -o=wide -l'
alias ksysgsec='kubectl --namespace=kube-system get secret'
alias ksysgsecl='kubectl --namespace=kube-system get secret -l'
alias ksysgsecojson='kubectl --namespace=kube-system get secret -o=json'
alias ksysgsecojsonl='kubectl --namespace=kube-system get secret -o=json -l'
alias ksysgsecowide='kubectl --namespace=kube-system get secret -o=wide'
alias ksysgsecowidel='kubectl --namespace=kube-system get secret -o=wide -l'
alias ksysgsecoyaml='kubectl --namespace=kube-system get secret -o=yaml'
alias ksysgsecoyamll='kubectl --namespace=kube-system get secret -o=yaml -l'
alias ksysgsecw='kubectl --namespace=kube-system get secret --watch'
alias ksysgsecwl='kubectl --namespace=kube-system get secret --watch -l'
alias ksysgsecwojson='kubectl --namespace=kube-system get secret --watch -o=json'
alias ksysgsecwojsonl='kubectl --namespace=kube-system get secret --watch -o=json -l'
alias ksysgsecwowide='kubectl --namespace=kube-system get secret --watch -o=wide'
alias ksysgsecwowidel='kubectl --namespace=kube-system get secret --watch -o=wide -l'
alias ksysgsecwoyaml='kubectl --namespace=kube-system get secret --watch -o=yaml'
alias ksysgsecwoyamll='kubectl --namespace=kube-system get secret --watch -o=yaml -l'
alias ksysgsl='kubectl --namespace=kube-system get --show-labels'
alias ksysgsll='kubectl --namespace=kube-system get --show-labels -l'
alias ksysgslowide='kubectl --namespace=kube-system get --show-labels -o=wide'
alias ksysgslowidel='kubectl --namespace=kube-system get --show-labels -o=wide -l'
alias ksysgslw='kubectl --namespace=kube-system get --show-labels --watch'
alias ksysgslwl='kubectl --namespace=kube-system get --show-labels --watch -l'
alias ksysgslwowide='kubectl --namespace=kube-system get --show-labels --watch -o=wide'
alias ksysgslwowidel='kubectl --namespace=kube-system get --show-labels --watch -o=wide -l'
alias ksysgsvc='kubectl --namespace=kube-system get service'
alias ksysgsvcl='kubectl --namespace=kube-system get service -l'
alias ksysgsvcojson='kubectl --namespace=kube-system get service -o=json'
alias ksysgsvcojsonl='kubectl --namespace=kube-system get service -o=json -l'
alias ksysgsvcowide='kubectl --namespace=kube-system get service -o=wide'
alias ksysgsvcowidel='kubectl --namespace=kube-system get service -o=wide -l'
alias ksysgsvcoyaml='kubectl --namespace=kube-system get service -o=yaml'
alias ksysgsvcoyamll='kubectl --namespace=kube-system get service -o=yaml -l'
alias ksysgsvcw='kubectl --namespace=kube-system get service --watch'
alias ksysgsvcwl='kubectl --namespace=kube-system get service --watch -l'
alias ksysgsvcwojson='kubectl --namespace=kube-system get service --watch -o=json'
alias ksysgsvcwojsonl='kubectl --namespace=kube-system get service --watch -o=json -l'
alias ksysgsvcwowide='kubectl --namespace=kube-system get service --watch -o=wide'
alias ksysgsvcwowidel='kubectl --namespace=kube-system get service --watch -o=wide -l'
alias ksysgsvcwoyaml='kubectl --namespace=kube-system get service --watch -o=yaml'
alias ksysgsvcwoyamll='kubectl --namespace=kube-system get service --watch -o=yaml -l'
alias ksysgw='kubectl --namespace=kube-system get --watch'
alias ksysgwl='kubectl --namespace=kube-system get --watch -l'
alias ksysgwojson='kubectl --namespace=kube-system get --watch -o=json'
alias ksysgwojsonl='kubectl --namespace=kube-system get --watch -o=json -l'
alias ksysgwowide='kubectl --namespace=kube-system get --watch -o=wide'
alias ksysgwowidel='kubectl --namespace=kube-system get --watch -o=wide -l'
alias ksysgwowidesl='kubectl --namespace=kube-system get --watch -o=wide --show-labels'
alias ksysgwowidesll='kubectl --namespace=kube-system get --watch -o=wide --show-labels -l'
alias ksysgwoyaml='kubectl --namespace=kube-system get --watch -o=yaml'
alias ksysgwoyamll='kubectl --namespace=kube-system get --watch -o=yaml -l'
alias ksysgwsl='kubectl --namespace=kube-system get --watch --show-labels'
alias ksysgwsll='kubectl --namespace=kube-system get --watch --show-labels -l'
alias ksysgwslowide='kubectl --namespace=kube-system get --watch --show-labels -o=wide'
alias ksysgwslowidel='kubectl --namespace=kube-system get --watch --show-labels -o=wide -l'
alias ksyslo='kubectl --namespace=kube-system logs -f'
alias ksyslop='kubectl --namespace=kube-system logs -f -p'
alias ksysrm='kubectl --namespace=kube-system delete'
alias ksysrmall='kubectl --namespace=kube-system delete --all'
alias ksysrmcm='kubectl --namespace=kube-system delete configmap'
alias ksysrmcmall='kubectl --namespace=kube-system delete configmap --all'
alias ksysrmcml='kubectl --namespace=kube-system delete configmap -l'
alias ksysrmdep='kubectl --namespace=kube-system delete deployment'
alias ksysrmdepall='kubectl --namespace=kube-system delete deployment --all'
alias ksysrmdepl='kubectl --namespace=kube-system delete deployment -l'
alias ksysrming='kubectl --namespace=kube-system delete ingress'
alias ksysrmingall='kubectl --namespace=kube-system delete ingress --all'
alias ksysrmingl='kubectl --namespace=kube-system delete ingress -l'
alias ksysrml='kubectl --namespace=kube-system delete -l'
alias ksysrmpo='kubectl --namespace=kube-system delete pods'
alias ksysrmpoall='kubectl --namespace=kube-system delete pods --all'
alias ksysrmpol='kubectl --namespace=kube-system delete pods -l'
alias ksysrmsec='kubectl --namespace=kube-system delete secret'
alias ksysrmsecall='kubectl --namespace=kube-system delete secret --all'
alias ksysrmsecl='kubectl --namespace=kube-system delete secret -l'
alias ksysrmsvc='kubectl --namespace=kube-system delete service'
alias ksysrmsvcall='kubectl --namespace=kube-system delete service --all'
alias ksysrmsvcl='kubectl --namespace=kube-system delete service -l'
alias ksysrun='kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
