MD004: false # Unordered list style - allow any style

# Other common rules
MD013: false # Line length - disable since it's common to have longer lines
# Configuration for markdownlint
# Allow HTML tags in markdown files
MD033:
  allowed_elements:
    - "div"
    - "img"
    - "p"
    - "br"
  enabled: true

# Turn off first line heading rule since we're using HTML alignment wrapper
MD041: false