export BASH_SILENCE_DEPRECATION_WARNING=1 # MacOS nuissance
export CLICOLORS=1 # Colorize as much as possible
export EDITOR=vim
export GPG_TTY=$(tty)
export JSH=$HOME/.jsh
export JSH_CUSTOM=$HOME/.jsh_local
export JSH_VERSION=$(cat $JSH/VERSION)
export PATH=$HOME/.bin:$HOME/go/bin:$PATH
export PYTHONDONTWRITEBYTECODE=1 # No .pyc files when importing
export SH=${SHELL##*/}
export SSHRC_EXTRAS='.inputrc .tmux.conf .vimrc'
export SOPS_AGE_KEY_FILE=$HOME/.sops/age.agekey
export VISUAL=vim
