---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

dotenv:
  - .env
  - "{{.ENV}}/.env."
  - "{{.HOME}}/.env"

env:
  PATH: /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:{{.PATH}}

includes:
  os: ".taskfiles/{{OS}}/taskfile.yaml"
  wsl: ".taskfiles/windows/taskfile.yaml"

tasks:
  chsh:
    cmd: chsh -s /bin/zsh
    status:
      - test "$(basename -- "$SHELL")" == "zsh"

  configure:
    cmds:
      - task: stow
      - task: chsh
      - task: git
      - task: os:configure
    desc: Configure OS-specific settings and applications

  default:
    cmd: task -l
    silent: true

  fzf:
    cmd: "{{.ROOT_DIR}}/.fzf/install --bin --no-zsh"
    preconditions:
      - test -x "{{.ROOT_DIR}}/.fzf/install"

  git:
    cmd: git submodule update --init --remote

  install:
    aliases:
      - init
      - provision
      - setup
    cmds:
      - task: install-deps
      - task: os:install
    desc: Provision installations and configurations

  install-casks:
    cmd: brew install --cask {{range .casks}}{{.}} {{end}}
    status:
      - test -z "{{.casks}}"

  install-deps:
    cmds:
      - task: fzf
      - task: install-homebrew
      - task: install-casks
      - task: install-formulae
      - task: install-links

  install-formulae:
    cmd: brew install {{range .formulae}}{{.}} {{end}}
    status:
      - test -z "{{.formulae}}"

  install-homebrew:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    status:
      - command -v brew

  install-links:
    cmd: brew install {{range .links}}{{.}} {{end}}
    status:
      - test -z "{{.links}}"

  setup:
    cmds:
      - task: configure
      - task: install
    desc: Configure and install jsh

  stow:
    cmd: stow . --adopt
    dir: "{{.ROOT_DIR}}"

  uninstall:
    cmd: stow -D .
    desc: Retract dotfiles from home directory
    dir: "{{.ROOT_DIR}}"

  upgrade:
    cmds:
      - cmd: brew upgrade
      - task: os:upgrade
    desc: Upgrade brew packages

version: 3
