---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

dotenv:
  - .env
  - "{{.ENV}}/.env."
  - "{{.HOME}}/.env"

includes:
  os: ".taskfiles/{{OS}}/taskfile.yaml"
  wsl: ".taskfiles/windows/taskfile.yaml"

tasks:
  chsh:
    cmd: chsh -s /bin/zsh
    desc: Change shell to Zsh
    status:
      - test "$(basename -- "$SHELL")" == "zsh"

  configure:
    cmds:
      - task: stow
      - task: chsh
      - task: configure-links
      - task: os:configure
    desc: Configure OS-specific settings and applications

  default:
    cmd: task -l
    desc: List all available tasks
    silent: true

  install:
    cmds:
      - task: install-casks
      - task: install-formulae
      - task: os:install
      - task: start-services
    desc: Install OS specific packages and Homebrew packages

  install-casks:
    cmd: brew install --force --cask {{range .casks}}{{.}} {{end}}
    desc: Install Homebrew casks

  install-formulae:
    cmd: brew install --force {{range .formulae}}{{.}} {{end}}
    desc: Install Homebrew formulae

  configure-links:
    cmd: brew link --overwrite --force {{range .links}}{{.}} {{end}}
    desc: Override brew links for formulae

  mount:
    cmd: "{{.ROOT_DIR}}/scripts/unix/configure-mounts.sh {{.CLI_ARGS}}"
    desc: "Configure and mount SMB shares. Usage: task mount [mount_name]"
    dir: "{{.ROOT_DIR}}"
    interactive: true

  setup:
    cmds:
      - task: install
      - task: configure
    desc: Install and configure jsh

  start-services:
    cmd: brew services start {{range .services}}{{.}} {{end}}
    desc: Start brew services

  stow:
    cmds:
      - |
        echo "🔍 Checking for broken symlinks in home directory..."
        find ~ -maxdepth 1 -type l ! -exec test -e {} \; -print | while read -r link; do
          echo "🗑️  Removing broken symlink: $link"
          rm "$link"
        done
      - stow -vvv . --adopt
      - echo "✅ Dotfiles deployed successfully"
    desc: Deploy dotfiles to home directory using GNU stow
    dir: "{{.ROOT_DIR}}"
    silent: true

  uninstall:
    cmds:
      - stow -D .
      - "{{.ROOT_DIR}}/scripts/unix/uninstall-homebrew.sh"
    desc: Retract dotfiles and completely uninstall Homebrew
    dir: "{{.ROOT_DIR}}"
    interactive: true

  update:
    cmds:
      - cmd: zinit self-update
      - cmd: zinit update --all
      - cmd: brew update
      - cmd: brew upgrade
      - task: os:upgrade
    desc: Upgrade brew packages and OS-specific packages

version: 3
