---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  os: ./taskfile_{{OS}}.yaml

tasks:

  default:
    cmd: task -l
    silent: true

  git:
    desc: Update git repo
    cmds:
      - git submodule update --init

  install:
    desc: Install packages and stow
    deps:
      - task: git
      - task: os
    cmds:
      - task: stow

  install-fzf:
    desc: Run upstream install
    cmds:
      - '{{.ROOT_DIR}}/.fzf/install --bin --no-zsh'
    preconditions:
      - test -x {{.ROOT_DIR}}/.fzf/install

  stow:
    desc: Propagate dotfiles from the current directory to the home directory
    dir: '{{.ROOT_DIR}}'
    cmd: stow . --adopt

  uninstall:
    desc: Retract dotfiles from home directory
    dir: '{{.ROOT_DIR}}'
    cmd: stow -D .
