---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

dotenv:
  - ".env"
  - "{{.ENV}}/.env."
  - "{{.HOME}}/.env"

includes:
  os: ".taskfiles/{{OS}}/taskfile.yaml"
  os:windows: ".taskfiles/windows/taskfile.yaml"

tasks:
  chsh:
    cmd: chsh -s /bin/zsh
    status:
      - test "$(basename -- "$SHELL")" == "zsh"

  default:
    cmd: task -l
    silent: true

  enable-service:
    cmd: brew services start {{range .services}}{{.}} {{end}}
    desc: Start services
    status:
      - test -z "{{.services}}"

  fzf:
    cmd: "{{.ROOT_DIR}}/.fzf/install --bin --no-zsh"
    preconditions:
      - test -x "{{.ROOT_DIR}}/.fzf/install"

  git:
    cmd: git submodule update --init

  install:
    aliases:
      - init
      - provision
      - setup
    cmds:
      - task: chsh
      - task: git
      - task: install-software
      - task: os
      - task: stow
    desc: Provision installations and configurations

  install-casks:
    cmd: brew install --cask {{range .casks}}{{.}} {{end}}
    status:
      - test -z "{{.casks}}"

  install-formulae:
    cmd: brew install {{range .formulae}}{{.}} {{end}}
    status:
      - test -z "{{.formulae}}"

  install-homebrew:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    status:
      - command -v brew

  install-links:
    cmd: brew install {{range .links}}{{.}} {{end}}
    status:
      - test -z "{{.links}}"

  install-packages:
    cmd:
      task: os:install-packages
    requires:
      vars:
        - packages

  install-software:
    cmds:
      - task: fzf
      - if grep -qi microsoft /proc/version; then task os:windows:install-apps; fi
      - task: install-packages
      - task: install-homebrew
      - task: install-casks
      - task: install-formulae
      - task: install-links
      - task: enable-service
    desc: Install apps, packages, casks, formulae, and links

  stow:
    cmd: stow . --adopt
    dir: "{{.ROOT_DIR}}"

  uninstall:
    cmd: stow -D .
    desc: Retract dotfiles from home directory
    dir: "{{.ROOT_DIR}}"

  upgrade:
    cmd: brew upgrade
    desc: Upgrade brew packages

version: 3
