---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  configure:
    cmds:
      - task: configure-sudoers
      - task: configure-wsl
    desc: Configure Linux system settings

  configure-sudoers:
    cmd: "{{.ROOT_DIR}}/scripts/linux/configure-sudoers.sh"
    desc: Configure sudoers file for passwordless sudo

  configure-wsl:
    cmds:
      - task: :wsl:configure
    desc: Configure WSL if detected
    status:
      - "! grep -qi microsoft /proc/version"

  install:
    cmds:
      - task: install-packages
      - task: install-wsl
    desc: Install packages and services

  install-packages:
    cmds:
      - task: update
      - cmd: sudo apt install -y {{range .packages}}{{.}} {{end}}
    requires:
      vars:
        - packages
    status:
      - test -z "{{.packages}}"

  install-wsl:
    cmds:
      - task: :wsl:install
    desc: Install WSL-specific packages if detected
    status:
      - "! grep -qi microsoft /proc/version"

  update:
    cmd: sudo apt update
    desc: Update package cache

  upgrade:
    cmds:
      - task: update
      - cmd: sudo apt upgrade -y
    desc: Update cache and upgrade all packages

vars:
  formulae:
    - helm # Kubernetes package manager
    - k9s # Kubernetes CLI To Manage Your Clusters In Style!
    - kind # Run local Kubernetes cluster in Docker
    - kubectl # Kubernetes command-line interface
    - neofetch # Fast, highly customisable system info script
    - syncthing # Open source continuous file synchronization application
    - terraform # Tool to build, change, and version infrastructure
  packages:
    - btop # Modern and colorful command line resource monitor
    - build-essential # Informational list of build-essential packages
    - cifs-utils # Common Internet File System utilities
    - dkms # Dynamic Kernel Module Support Framework
    - git # Fast, scalable, distributed revision control system
    - grc # Generic colouriser for everything
    - make # Utility for directing compilation
    - neovim # Heavily refactored vim fork
    - net-tools # NET-3 networking toolkit
    - npm # Package manager for Node.js
    - nvme-cli # NVMe management command line interface
    - pipx # Execute binaries from Python packages in isolated environments
    - python3 # Interactive high-level object-oriented language (default python3 version)
    - ripgrep # Recursively searches directories for a regex pattern
    - rsync # Fast, versatile, remote (and local) file-copying tool
    - s-tui # Terminal UI for monitoring your computer
    - tmux # Terminal multiplexer
    - wget # Retrieves files from the web
    - zsh # Shell with lots of features

  services:
    - syncthing

version: 3
