---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:

  configure:
    cmds:
      - task: enable-services
      - cmd: |
          if grep -qi microsoft /proc/version; then
            task wsl:configure
          fi

  default:
    cmds:
      - task: configure
      - task: install

  enable-services:
    cmd: brew services start {{range .services}}{{.}} {{end}}
    status:
      - test -z "{{.services}}"

  install:
    cmds:
      - task: install-packages
      - cmd: |
          if grep -qi microsoft /proc/version; then
            task wsl:install
          fi

  install-packages:
    cmds:
      - task: update
      - cmd: sudo apt install -y {{range .packages}}{{.}} {{end}}
    requires:
      vars:
        - packages

  update:
    cmd: sudo apt update

  upgrade:
    cmds:
      - task: update
      - cmd: sudo apt upgrade -y

vars:
  formulae:
    - helm
    - k9s
    - kind
    - kubectl
    - neofetch
    - sops
    - syncthing
    - terraform
  packages:
    - ansible
    - btop
    - build-essential
    - dkms
    - fzf
    - git
    - glances
    - grc
    - htop
    - libbz2-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libnss3-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - make
    - neovim
    - net-tools
    - npm
    - nvme-cli
    - python3
    - ripgrep
    - rsync
    - s-tui
    - stow
    - wget
    - zlib1g-dev
    - zsh
  services:
    - syncthing

version: 3
