---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  configure:
    cmds:
      - task: configure-sudoers
      - task: detect-wsl || task wsl:configure
    desc: Configure Linux system settings

  configure-sudoers:
    cmd: "{{.ROOT_DIR}}/scripts/linux/configure-sudoers.sh"
    desc: Configure sudoers file for passwordless sudo

  detect-wsl:
    internal: true
    cmd: grep -qi microsoft /proc/version
    silent: true
    desc: Check if running on WSL

  install:
    cmds:
      - task: install-packages
      - task: detect-wsl || task wsl:install
    desc: Install packages and services

  install-packages:
    cmds:
      - task: update
      - cmd: sudo apt install -y {{range .packages.packages}}{{.}} {{end}}
    desc: Update package cache and install packages

  update:
    cmd: sudo apt update
    desc: Update package cache

  upgrade:
    cmds:
      - task: update
      - cmd: sudo apt upgrade -y
    desc: Update cache and upgrade all packages

vars:
  formulae:
    - helm
    - k9s
    - kind
    - kubectl
    - neofetch
    - syncthing
    - terraform
  packages:
    - btop
    - build-essential
    - cifs-utils
    - dkms
    - git
    - grc
    - make
    - neovim
    - net-tools
    - npm
    - nvme-cli
    - pipx
    - python
    - ripgrep
    - rsync
    - s-tui
    - tmux
    - wget
    - zsh

  services:
    - syncthing

version: 3
