---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  default:
    cmds:
      - task: install-packages
      - if grep -qi microsoft /proc/version; then task wsl; fi

  install-packages:
    cmds:
      - task: update
      - sudo apt install -y {{range .packages}}{{.}} {{end}}
    requires:
      vars:
        - packages

  update:
    cmd: sudo apt update

  upgrade:
    cmds:
      - task: update
      - sudo apt upgrade -y
    desc: Upgrade OS packages

vars:
  formulae:
    - helm
    - k9s
    - kind
    - kubectl
    - nerdfetch
    - syncthing
  packages:
    - ansible
    - btop
    - build-essential
    - dkms
    - fzf
    - git
    - glances
    - grc
    - htop
    - libbz2-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libnss3-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - make
    - neovim
    - net-tools
    - npm
    - nvme-cli
    - python3
    - s-tui
    - software-properties-common
    - stow
    - wget
    - zlib1g-dev
    - zsh
  services:
    - syncthing

version: 3
