---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  configure:
    cmds:
      - task: configure-sudoers
      - task: configure-wsl
    desc: Configure Linux system settings

  configure-sudoers:
    cmd: "{{.ROOT_DIR}}/scripts/linux/configure-sudoers.sh"
    desc: Configure sudoers file for passwordless sudo

  configure-wsl:
    cmds:
      - task: :wsl:configure
    desc: Configure WSL if detected
    status:
      - "! grep -qi microsoft /proc/version"

  install:
    cmds:
      - task: install-packages
      - task: install-wsl
    desc: Install packages and services

  install-packages:
    cmds:
      - task: update
      - cmd: sudo apt install -y {{range .packages}}{{.}} {{end}}
    requires:
      vars:
        - packages
    status:
      - test -z "{{.packages}}"

  install-wsl:
    cmds:
      - task: :wsl:install
    desc: Install WSL-specific packages if detected
    status:
      - "! grep -qi microsoft /proc/version"

  update:
    cmd: sudo apt update
    desc: Update package cache

  upgrade:
    cmds:
      - task: update
      - cmd: sudo apt upgrade -y
    desc: Update cache and upgrade all packages

vars:
  formulae:
    - age # Simple, modern, secure file encryption
    - awscli # Official Amazon AWS command-line interface
    - bat # Clone of cat(1) with syntax highlighting and Git integration
    - btop # Resource monitor. C++ version and continuation of bashtop and bpytop
    - cloudflared # Cloudflare Tunnel client (formerly Argo Tunnel)
    - coreutils # GNU File, Shell, and Text utilities
    - curl # Get a file from an HTTP, HTTPS or FTP server
    - diffutils # GNU diff utilities
    - direnv # Load/unload environment variables based on $PWD
    - docker # Pack, ship and run any application as a lightweight container
    - dos2unix # Convert text between DOS, UNIX, and Mac formats
    - exiftool # Perl lib for reading and writing EXIF metadata
    - eza # Modern, maintained replacement for ls
    - fastfetch # Like neofetch, but much faster because written mostly in C
    - ffmpeg # Play, record, convert, and stream audio and video
    - gawk # GNU awk utility
    - gemini-cli # Interact with Google Gemini AI models from the command-line
    - gh # GitHub command-line tool
    - git # Distributed revision control system
    - gnu-sed # GNU implementation of the famous stream editor
    - go # Open source programming language to build simple/reliable/efficient software
    - grc # Colorize logfiles and command output
    - grep # GNU grep, egrep and fgrep
    - helm # Kubernetes package manager
    - helmfile # Deploy Kubernetes Helm Charts
    - hugo # Configurable static site generator
    - ipmitool # Utility for IPMI control with kernel driver or LAN interface
    - jq # Lightweight and flexible command-line JSON processor
    - k9s # Kubernetes CLI To Manage Your Clusters In Style!
    - kind # Run local Kubernetes cluster in Docker
    - krew # Package manager for kubectl plugins
    - kubecm # KubeConfig Manager
    - kubecolor # Colorize your kubectl output
    - kubernetes-cli # Kubernetes command-line interface
    - kubescape # Kubernetes testing according to Hardening Guidance by NSA and CISA
    - kubetail # Logging tool for Kubernetes with a real-time web dashboard
    - make # Utility for directing compilation
    - mpv # Media player based on MPlayer and mplayer2
    - neofetch # Fast, highly customisable system info script
    - neovim # Ambitious Vim-fork focused on extensibility and agility
    - netcat # Utility for managing network connections
    - nmap # Port scanning utility for large networks
    - node # Open-source, cross-platform JavaScript runtime environment
    - opentofu # Drop-in replacement for Terraform. Infrastructure as Code Tool
    - pipx # Execute binaries from Python packages in isolated environments
    - poetry # Python package management tool
    - prettier # Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
    - python # Interpreted, interactive, object-oriented programming language
    - qwen-code # AI-powered command-line workflow tool for developers
    - readline # Library for command-line editing
    - ripgrep # Search tool like grep and The Silver Searcher
    - rsync # Utility that provides fast incremental file transfer
    - sops # Editor of encrypted files
    - speedtest-cli # Command-line interface for https://speedtest.net bandwidth tests
    - sshpass # Non-interactive SSH password auth
    - stow # Organize software neatly under a single directory tree (e.g. /usr/local)
    - syncthing # Open source continuous file synchronization application
    - talosctl # CLI for out-of-band management of Kubernetes nodes created by Talos
    - terraform # Tool to build, change, and version infrastructure
    - tldr # Simplified and community-driven man pages
    - tlrc # Official tldr client written in Rust
    - tmux # Terminal multiplexer
    - tree # Display directories as trees (with optional color/HTML output)
    - uv # Extremely fast Python package installer and resolver, written in Rust
    - vim # Vi 'workalike' with many additional features
    - watch # Executes a program periodically, showing output fullscreen
    - wget # Internet file retriever
    - xh # Friendly and fast tool for sending HTTP requests
    - xz # General-purpose data compression with high compression ratio
    - yq # Process YAML, JSON, XML, CSV and properties documents from the CLI
    - zoxide # Shell extension to navigate your filesystem faster
    - zsh # UNIX shell (command interpreter)
  packages:
    - build-essential # Informational list of build-essential packages
    - cifs-utils # Common Internet File System utilities
    - dkms # Dynamic Kernel Module Support Framework
    - net-tools # NET-3 networking toolkit
    - nvme-cli # NVMe management command line interface
    - s-tui # Terminal UI for monitoring your computer

  services:
    - syncthing

version: 3
