---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  configure:
    cmds:
      - task: configure-ghostty
      - echo ""
      - echo "⚠️  The following apps need to be launched first before they can be configured:"
      - echo ""
      - echo "🦊 Firefox - Open the app, then run:"
      - echo "   task os:configure-firefox"
      - echo ""
      - echo "📦 VSCode - Open the app, then run:"
      - echo "   task os:configure-vscode"
    desc: Configure all macOS applications and settings
    silent: true

  configure-firefox:
    cmd: ln -sf $HOME/.jsh/configs/firefox/user.js "{{ .FF_DIR }}/user.js"
    desc: Tweak Firefox using Betterfox + own enhancements
    preconditions:
      - test -d /Applications/Firefox.app
      - test -d $HOME/Library/Application\ Support/Firefox/Profiles/
    vars:
      FF_DIR:
        sh: 'find $HOME/Library/Application\ Support/Firefox/Profiles -type d -name "*.default-release"'

  configure-ghostty:
    cmd: bash $HOME/.jsh/scripts/macos/configure-ghostty-aliases.sh
    desc: Create launcher apps for Ghostty (Term.app and Terminal.app)
    preconditions:
      - test -d /Applications/Ghostty.app

  configure-vscode:
    cmds:
      - ln -sf $HOME/.jsh/configs/vscode/keybindings.json "$HOME/Library/Application Support/Code/User/keybindings.json"
      - ln -sf $HOME/.jsh/configs/vscode/settings.json "$HOME/Library/Application Support/Code/User/settings.json"
    desc: Override VSCode settings with local copy using symlink
    generates:
      - "$HOME/Library/Application Support/Code/User/keybindings.json"
      - "$HOME/Library/Application Support/Code/User/settings.json"
    preconditions:
      - test -d /Applications/Visual\ Studio\ Code.app
      - test -d $HOME/Library/Application\ Support/Code/User/

  install:
    cmd: echo "No further steps required for macOS"
    desc: No-op install task

  upgrade:
    cmds:
      - |
        if command -v mas &> /dev/null; then
          echo "📦 Upgrading Mac App Store apps..."
          mas upgrade
        else
          echo "⚠️  mas not installed - skipping App Store updates"
          echo "   Install with: brew install mas"
        fi
    desc: Upgrade Mac App Store apps using mas
    silent: true

vars:
  casks:
    - appcleaner # Application uninstaller
    - bitwarden # Desktop password and login vault
    - brave-browser # Web browser focusing on privacy
    - caffeine # Utility that prevents the system from going to sleep
    - claude-code # Terminal-based AI coding assistant
    - firefox # Web browser
    - font-jetbrains-mono-nerd-font # JetBrainsMono Nerd Font families (JetBrains Mono)
    - ghostty # Terminal emulator that uses platform-native UI and GPU acceleration
    - istat-menus # System monitoring app
    - keyboardcleantool # Blocks all Keyboard and TouchBar input
    - macfuse # File system integration
    - mounty # Re-mounts write-protected NTFS volumes
    - openvpn-connect # Client program for the OpenVPN Access Server
    - orbstack # Replacement for Docker Desktop
    - plexamp # Music player focusing on visuals
    - scroll-reverser # Tool to reverse the direction of scrolling
    - signal # Instant messaging application focusing on security
    - spotify # Music streaming service
    - sublime-text # Text editor for code, markup and prose
    - tailscale-app # Mesh VPN based on WireGuard
    - todoist-app # To-do list
    - visual-studio-code # Open-source code editor
    - wifiman # Network monitoring and troubleshooting tool
    - zoom # Video communication and virtual meeting platform

  formulae:
    - age # Simple, modern, secure file encryption
    - awscli # Official Amazon AWS command-line interface
    - bat # Clone of cat(1) with syntax highlighting and Git integration
    - btop # Resource monitor. C++ version and continuation of bashtop and bpytop
    - cloudflared # Cloudflare Tunnel client (formerly Argo Tunnel)
    - coreutils # GNU File, Shell, and Text utilities
    - curl # Get a file from an HTTP, HTTPS or FTP server
    - diffutils # GNU diff utilities
    - direnv # Load/unload environment variables based on $PWD
    - docker # Pack, ship and run any application as a lightweight container
    - dos2unix # Convert text between DOS, UNIX, and Mac formats
    - exiftool # Perl lib for reading and writing EXIF metadata
    - eza # Modern, maintained replacement for ls
    - fastfetch # Like neofetch, but much faster because written mostly in C
    - ffmpeg # Play, record, convert, and stream audio and video
    - fileicon # macOS CLI for managing custom icons for files and folders
    - gawk # GNU awk utility
    - gemini-cli # Interact with Google Gemini AI models from the command-line
    - gh # GitHub command-line tool
    - git # Distributed revision control system
    - gnu-sed # GNU implementation of the famous stream editor
    - go # Open source programming language to build simple/reliable/efficient software
    - grc # Colorize logfiles and command output
    - grep # GNU grep, egrep and fgrep
    - gromgit/fuse/ntfs-3g-mac # Read-write NTFS driver for FUSE
    - helm # Kubernetes package manager
    - helmfile # Deploy Kubernetes Helm Charts
    - hugo # Configurable static site generator
    - ipmitool # Utility for IPMI control with kernel driver or LAN interface
    - jq # Lightweight and flexible command-line JSON processor
    - k9s # Kubernetes CLI To Manage Your Clusters In Style!
    - kind # Run local Kubernetes cluster in Docker
    - krew # Package manager for kubectl plugins
    - kubecm # KubeConfig Manager
    - kubecolor # Colorize your kubectl output
    - kubernetes-cli # Kubernetes command-line interface
    - kubescape # Kubernetes testing according to Hardening Guidance by NSA and CISA
    - kubetail # Logging tool for Kubernetes with a real-time web dashboard
    - make # Utility for directing compilation
    - mas # Mac App Store command-line interface
    - mpv # Media player based on MPlayer and mplayer2
    - neofetch # Fast, highly customisable system info script
    - neovim # Ambitious Vim-fork focused on extensibility and agility
    - netcat # Utility for managing network connections
    - nmap # Port scanning utility for large networks
    - node # Open-source, cross-platform JavaScript runtime environment
    - ntfs-3g-mac # Read-write NTFS driver for FUSE
    - opentofu # Drop-in replacement for Terraform. Infrastructure as Code Tool
    - pipx # Execute binaries from Python packages in isolated environments
    - poetry # Python package management tool
    - prettier # Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
    - python # Interpreted, interactive, object-oriented programming language
    - qwen-code # AI-powered command-line workflow tool for developers
    - readline # Library for command-line editing
    - ripgrep # Search tool like grep and The Silver Searcher
    - rsync # Utility that provides fast incremental file transfer
    - sops # Editor of encrypted files
    - speedtest-cli # Command-line interface for https://speedtest.net bandwidth tests
    - sshpass # Non-interactive SSH password auth
    - stow # Organize software neatly under a single directory tree (e.g. /usr/local)
    - syncthing # Open source continuous file synchronization application
    - talosctl # CLI for out-of-band management of Kubernetes nodes created by Talos
    - terraform # Tool to build, change, and version infrastructure
    - tldr # Simplified and community-driven man pages
    - tlrc # Official tldr client written in Rust
    - tmux # Terminal multiplexer
    - tree # Display directories as trees (with optional color/HTML output)
    - uv # Extremely fast Python package installer and resolver, written in Rust
    - vim # Vi 'workalike' with many additional features
    - watch # Executes a program periodically, showing output fullscreen
    - wget # Internet file retriever
    - xh # Friendly and fast tool for sending HTTP requests
    - xz # General-purpose data compression with high compression ratio
    - yq # Process YAML, JSON, XML, CSV and properties documents from the CLI
    - zoxide # Shell extension to navigate your filesystem faster
    - zsh # UNIX shell (command interpreter)

  links:
    - mpv

  services:
    - syncthing

version: 3
