---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  configure:
    cmds:
      - task: configure-firefox
      - task: configure-vscode
    desc: Configure all macOS applications and settings

  configure-firefox:
    cmds:
      - ln -sf $HOME/.jsh/configs/firefox/user.js "{{ .FF_DIR }}/user.js"
    desc: Tweak Firefox using Betterfox + own enhancements
    preconditions:
      - test -d /Applications/Firefox.app
      - test -d $HOME/Library/Application\ Support/Firefox/Profiles/
    vars:
      FF_DIR:
        sh: 'find $HOME/Library/Application\ Support/Firefox/Profiles -type d -name "*.default-release"'

  configure-vscode:
    cmds:
      - ln -sf $HOME/.jsh/configs/vscode/keybindings.json "$HOME/Library/Application Support/Code/User/keybindings.json"
      - ln -sf $HOME/.jsh/configs/vscode/settings.json "$HOME/Library/Application Support/Code/User/settings.json"
    desc: Override VSCode settings with local copy using symlink
    generates:
      - "$HOME/Library/Application Support/Code/User/keybindings.json"
      - "$HOME/Library/Application Support/Code/User/settings.json"

  install:
    cmd: echo "No further steps required for macOS"
    desc: No-op install task

vars:
  casks:
    - caffeine
    - firefox
    - font-jetbrains-mono-nerd-font
    - google-chrome
    - macfuse
    - mounty
    - stolendata-mpv # for app, not `mpv` CLI
    - sublime-text
    - tailscale-app
    - todoist-app
    - visual-studio-code
    - wifiman
    - zoom

  formulae:
    - age
    - awscli
    - bat
    - btop
    - cloudflared
    - direnv
    - docker
    - exiftool
    - ffmpeg
    - gawk # GNU awk
    - gnu-sed
    - go
    - grc
    - grep
    - gromgit/fuse/ntfs-3g-mac
    - helm
    - helmfile
    - hugo
    - ipmitool
    - k9s
    - kind
    - krew
    - kubecm
    - kubecolor
    - kubernetes-cli
    - kubescape
    - kubetail
    - neofetch
    - netcat
    - nmap
    - poetry
    - readline
    - ripgrep
    - rsync
    - sops
    - sshpass
    - syncthing
    - tailscale
    - talosctl
    - tldr
    - tmux
    - watch
    - xz
    - zoxide

  services:
    - syncthing
    - tailscale

version: 3
