---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:

  configure-firefox:
    cmds:
      - ln -sf $HOME/.jsh/configs/user.js "{{ .FF_DIR }}/user.js"
    desc: Tweak Firefox using Betterfox + own enhancements
    preconditions:
      - test -d /Applications/Firefox.app
      - test -d $HOME/Library/Application\ Support/Firefox/Profiles/
    vars:
      FF_DIR:
        sh: 'find $HOME/Library/Application\ Support/Firefox/Profiles -type d -name
          "*.default-release"'

  configure-iterm2:
    cmds:
      - defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string
        '{{.HOME}}/.config/iterm2'
      - defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder
        -bool true
    desc: Set iTerm2 to read config from local copy

  configure-vscode:
    cmds:
      - ln -sf $HOME/.jsh/configs/vscode.settings.json
        "$HOME/Library/Application Support/Code/User/settings.json"
    desc: Override VSCode settings with local copy using symlink
    generates:
      - "$HOME/Library/Application Support/Code/User/settings.json"

  default:
    cmds:
      - task: set-symlinks
      - task: configure-firefox
      - task: configure-iterm2
      - task: configure-vscode

  enable-service:
    cmds:
      - brew services start {{.service}}
    desc: Start and enable services
    requires:
      vars:
        - service

  set-symlinks:
    cmds:
      - ln -sf $(brew --prefix)/bin/ggrep /usr/local/bin/grep
    desc: Set up symlinks to dotfiles

vars:
  casks:
    - caffeine
    - discord
    - firefox
    - font-meslo-lg-nerd-font
    - foobar2000
    - iterm2
    - plex
    - plexamp
    - raspberry-pi-imager
    - signal
    - slack
    - spotify
    - stolendata-mpv # app, not just CLI like `mpv`
    - sublime-text
    - telegram
    - tg-pro
    - visual-studio-code
    - zoom
  formulae:
    - age
    - ansible
    - ansible-lint
    - argocd
    - awscli
    - bat
    - btop
    - cilium-cli
    - cloudflared
    - direnv
    - docker
    - exiftool
    - ffmpeg
    - fluxcd/tap/flux
    - fzf
    - git-delta
    - glances
    - gnu-sed
    - go
    - go-task
    - govc
    - grc
    - grep
    - helm
    - helmfile
    - hugo
    - ipmitool
    - johanhaleby/kubetail/kubetail
    - jq
    - k3sup
    - k9s
    - kind
    - krew
    - kubecm
    - kubecolor
    - kubectx
    - kubent
    - kubernetes-cli
    - kubescape
    - kubeshark
    - kubetail
    - libvirt
    - neofetch
    - neovim
    - netcat
    - nmap
    - nvim
    - podman
    - poetry
    - python3
    - qemu
    - readline
    - rsync
    - siderolabs/tap/talosctl
    - sops
    - sshpass
    - stow
    - syncthing
    - tailscale
    - talosctl
    - tldr
    - tmux
    - tree
    - tree-sitter
    - unbound
    - virtualenv
    - watch
    - xz
    - zoxide
    - zsh-completions
  links:
    - ansible
    - docker
    - python3
  services:
    - syncthing

version: "3"
