---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  configure:
    cmds:
      - task: configure-ghostty
      - echo "⚠️  The following apps need to be launched first before they can be configured:"
      - echo ""
      - echo "🦊 Firefox - Open the app, then run:"
      - echo "   task os:configure-firefox"
      - echo ""
      - echo "📦 VSCode - Open the app, then run:"
      - echo "   task os:configure-vscode"
    desc: Configure all macOS applications and settings
    silent: true

  configure-firefox:
    cmd: ln -sf $HOME/.jsh/configs/firefox/user.js "{{ .FF_DIR }}/user.js"
    desc: Tweak Firefox using Betterfox + own enhancements
    preconditions:
      - test -d /Applications/Firefox.app
      - test -d $HOME/Library/Application\ Support/Firefox/Profiles/
    vars:
      FF_DIR:
        sh: 'find $HOME/Library/Application\ Support/Firefox/Profiles -type d -name "*.default-release"'

  configure-ghostty:
    cmd: bash $HOME/.jsh/scripts/macos/configure-ghostty-aliases.sh
    desc: Create launcher apps for Ghostty (Term.app and Terminal.app)
    preconditions:
      - test -d /Applications/Ghostty.app

  configure-vscode:
    cmds:
      - ln -sf $HOME/.jsh/configs/vscode/keybindings.json "$HOME/Library/Application Support/Code/User/keybindings.json"
      - ln -sf $HOME/.jsh/configs/vscode/settings.json "$HOME/Library/Application Support/Code/User/settings.json"
    desc: Override VSCode settings with local copy using symlink
    generates:
      - "$HOME/Library/Application Support/Code/User/keybindings.json"
      - "$HOME/Library/Application Support/Code/User/settings.json"
    preconditions:
      - test -d /Applications/Visual\ Studio\ Code.app
      - test -d $HOME/Library/Application\ Support/Code/User/

  install:
    cmd: echo "No further steps required for macOS"
    desc: No-op install task

vars:
  casks:
    - caffeine # Utility that prevents the system from going to sleep
    - ghostty # Fast, feature-rich, and cross-platform terminal emulator
    - macfuse # File system integration
    - mounty # Re-mounts write-protected NTFS volumes
    - sublime-text # Text editor for code, markup and prose
    - tailscale-app # Mesh VPN based on WireGuard
    - todoist-app # To-do list
    - visual-studio-code # Open-source code editor
    - wifiman # Network monitoring and troubleshooting tool
    - zoom # Video communication and virtual meeting platform

  formulae:
    - age # Simple, modern, secure file encryption
    - awscli # Official Amazon AWS command-line interface
    - bat # Clone of cat(1) with syntax highlighting and Git integration
    - btop # Resource monitor. C++ version and continuation of bashtop and bpytop
    - cloudflared # Cloudflare Tunnel client (formerly Argo Tunnel)
    - direnv # Load/unload environment variables based on $PWD
    - docker # Pack, ship and run any application as a lightweight container
    - exiftool # Perl lib for reading and writing EXIF metadata
    - eza # Modern, maintained replacement for ls
    - ffmpeg # Play, record, convert, and stream audio and video
    - gawk # GNU awk utility
    - gh # GitHub command-line tool
    - gnu-sed # GNU implementation of the famous stream editor
    - go # Open source programming language to build simple/reliable/efficient software
    - grc # Colorize logfiles and command output
    - grep # GNU grep, egrep and fgrep
    - gromgit/fuse/ntfs-3g-mac # Read-write NTFS driver for FUSE
    - helm # Kubernetes package manager
    - helmfile # Deploy Kubernetes Helm Charts
    - hugo # Configurable static site generator
    - ipmitool # Utility for IPMI control with kernel driver or LAN interface
    - k9s # Kubernetes CLI To Manage Your Clusters In Style!
    - kind # Run local Kubernetes cluster in Docker
    - krew # Package manager for kubectl plugins
    - kubecm # KubeConfig Manager
    - kubecolor # Colorize your kubectl output
    - kubernetes-cli # Kubernetes command-line interface
    - kubescape # Kubernetes testing according to Hardening Guidance by NSA and CISA
    - kubetail # Logging tool for Kubernetes with a real-time web dashboard
    - neofetch # Fast, highly customisable system info script
    - mpv # Media player based on MPlayer and mplayer2
    - netcat # Utility for managing network connections
    - nmap # Port scanning utility for large networks
    - poetry # Python package management tool
    - readline # Library for command-line editing
    - ripgrep # Search tool like grep and The Silver Searcher
    - rsync # Utility that provides fast incremental file transfer
    - sops # Editor of encrypted files
    - sshpass # Non-interactive SSH password auth
    - syncthing # Open source continuous file synchronization application
    - talosctl # CLI for out-of-band management of Kubernetes nodes created by Talos
    - terraform # Tool to build, change, and version infrastructure
    - tldr # Simplified and community-driven man pages
    - tmux # Terminal multiplexer
    - watch # Executes a program periodically, showing output fullscreen
    - xh # Friendly and fast tool for sending HTTP requests
    - xz # General-purpose data compression with high compression ratio
    - zoxide # Shell extension to navigate your filesystem faster

  links:
    - mpv

  services:
    - syncthing

version: 3
