---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
tasks:
  configure-firefox:
    cmds:
      - ln -sf $HOME/.jsh/configs/user.js $HOME/Library/Application\
        Support/Firefox/Profiles/*.default-release/user.js
    desc: Tweak Firefox using Betterfox + own enhancements
    preconditions:
      - test -d /Applications/Firefox.app
      - test -d $HOME/Library/Application\ Support/Firefox/Profiles/

  configure-iterm2:
    cmds:
      - defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string
        '{{.HOME}}/.config/iterm2'
      - defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder
        -bool true
    desc: Set iTerm2 to read config from local copy

  configure-vscode:
    cmds:
      - ln -sf $HOME/.jsh/configs/vscode.settings.json
        "$HOME/Library/Application Support/Code/User/settings.json"
    desc: Override VSCode settings with local copy using symlink
    generates:
      - "$HOME/Library/Application Support/Code/User/settings.json"
  default:
    deps:
      - install-packages
      - install-casks
      - install-links
      - set-symlinks
      - configure-firefox
      - configure-iterm2
      - configure-vscode

  set-symlinks:
    cmds:
      - ln -sf /opt/homebrew/bin/ggrep /opt/homebrew/bin/grep
    desc: Set up symlinks to dotfiles

  upgrade:
    cmd: brew upgrade
    desc: Upgrade brew packages

vars:
  casks:
    - alfred
    - alt-tab
    - brave-browser
    - caffeine
    - chatgpt
    - discord
    - drawio
    - firefox
    - font-meslo-lg-nerd-font
    - foobar2000
    - google-chrome
    - iterm2
    - lens
    - mos
    - notion
    - omnidisksweeper
    - plex
    - plexamp
    - raspberry-pi-imager
    - signal
    - slack
    - spotify
    - stolendata-mpv # app, not just CLI like `mpv`
    - sublime-text
    - telegram
    - tg-pro
    - visual-studio-code
    - zoom
  links:
    - ansible
    - docker
    - python3
  formulae:
    - age
    - ansible
    - ansible-lint
    - argocd
    - awscli
    - bat
    - btop
    - cilium-cli
    - cloudflared
    - corepack
    - coreutils
    - cryptography
    - direnv
    - docker
    - exiftool
    - ffmpeg
    - flox
    - fluxcd/tap/flux
    - fzf
    - git-delta
    - glances
    - gnu-sed
    - gnutls
    - go
    - go-task
    - govc
    - grc
    - grep
    - helm
    - helmfile
    - hugo
    - ipmitool
    - johanhaleby/kubetail/kubetail
    - jq
    - k3sup
    - k9s
    - kind
    - krew
    - kubecm
    - kubecolor
    - kubectx
    - kubent
    - kubernetes-cli
    - kubescape
    - kubeshark
    - kubetail
    - libassuan
    - libde265
    - libev
    - libevent
    - libffi
    - libgcrypt
    - libgpg-error
    - libheif
    - libidn2
    - libksba
    - liblqr
    - libomp
    - libpng
    - libtasn1
    - libtiff
    - libtool
    - libunistring
    - libusb
    - libvirt
    - libyaml
    - little-cms2
    - llvm
    - lua
    - mailsy
    - mas
    - minikube
    - mos
    - ncdu
    - ncurses
    - neofetch
    - neovim
    - netcat
    - nettle
    - nmap
    - node
    - npm
    - nvim
    - oniguruma
    - perl
    - pkg-config
    - podman
    - poetry
    - python-certifi
    - python-cryptography
    - python-dateutil
    - python-distlib
    - python-filelock
    - python-jinja
    - python-lxml
    - python-markupsafe
    - python-platformdirs
    - python-pyparsing
    - python-pytz
    - python3
    - pyyaml
    - qemu
    - readline
    - rsync
    - siderolabs/tap/talosctl
    - sops
    - sshpass
    - stow
    - syncthing
    - tailscale
    - talosctl
    - terraform
    - tesseract
    - tldr
    - tmux
    - tree
    - tree-sitter
    - unbound
    - utf8proc
    - virtualenv
    - watch
    - wireshark
    - xz
    - z
    - z3
    - zoxide
    - zsh-completions

version: "3"
