---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  configure:
    cmds:
      - task: configure-ssh
      - task: configure-terminal
      - task: configure-vscode
      - task: configure-firefox
    desc: Configure Windows system settings and applications

  configure-firefox:
    cmd: "{{.ROOT_DIR}}/scripts/windows/configure-firefox.sh"
    desc: Configure Firefox settings

  configure-ssh:
    cmd: "{{.ROOT_DIR}}/scripts/windows/configure-ssh.sh"
    desc: Configure SSH settings

  configure-terminal:
    cmd: "{{.ROOT_DIR}}/scripts/windows/configure-terminal.sh"
    desc: Configure Windows Terminal

  configure-vscode:
    cmd: "{{.ROOT_DIR}}/scripts/windows/configure-vscode.sh"
    desc: Configure Visual Studio Code

  default:
    cmds:
      - task: configure
      - task: install
    desc: Default task (configure then install)

  install:
    cmds:
      - task: install-apps
      - task: install-nerd-fonts
    desc: Install applications and fonts

  install-apps:
    cmd: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command 'Start-Process -FilePath "winget" -ArgumentList "install {{range .apps}}{{.}} {{end}}" -Verb RunAs -Wait'
    desc: Install applications via winget

  install-nerd-fonts:
    cmd: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command 'Start-Process powershell -ArgumentList "refreshenv; choco install {{range .fonts}}nerd-fonts-{{.}} {{end}} -y" -Verb RunAs -Wait'
    status:
      - |
        {{range .fonts}}
        ls /mnt/c/Windows/Fonts | grep -qi "{{.}}"
        {{end}}
    desc: Install Nerd fonts via Chocolatey

vars:
  apps:
    - Chocolatey.Chocolatey # Software management automation for Windows
    - Doist.Todoist # To-do list and task manager
    - DuckDuckGo.DesktopBrowser # Privacy-focused web browser
    - Git.Git # Distributed version control system
    - Microsoft.PowerToys # Set of utilities for power users
    - Microsoft.VisualStudioCode # Code editor redefined and optimized for building and debugging
    - Microsoft.WindowsTerminal # Modern terminal application for command-line tools
    - Mozilla.Firefox # Fast, Private & Safe Web Browser
    - Rufus.Rufus # Create bootable USB drives the easy way
    - Syncthing.Syncthing # Open source continuous file synchronization
    - Zoom.Zoom # Video conferencing and web conferencing service
    - mpv.net # Modern media player for Windows

  fonts:
    - JetBrainsMono

version: 3
