---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  configure:
    cmds:
      - echo "⚠️  The following apps need to be launched first before they can be configured:"
      - echo ""
      - echo "📦 VSCode - Open the app, then run:"
      - echo "   task os:configure-vscode"
      - echo ""
      - echo "📝 Configuring SSH and Terminal..."
      - task: configure-hostname
      - task: configure-ssh
      - task: configure-terminal
    desc: Configure Windows system settings and applications
    silent: true

  configure-hostname:
    cmd: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command 'Start-Process powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command `"$$current = [System.Net.Dns]::GetHostName(); if ($$current -ne ''{{.HOSTNAME}}'') { Write-Host ''🖥️  Setting hostname to {{.HOSTNAME}}...''; Rename-Computer -NewName ''{{.HOSTNAME}}'' -Force; Write-Host ''⚠️  Restart required for hostname change to take effect'' } else { Write-Host ''✅ Hostname already set to {{.HOSTNAME}}'' }`"" -Verb RunAs -Wait'
    desc: Configure Windows hostname
    silent: true

  configure-ssh:
    cmd: "{{.ROOT_DIR}}/scripts/windows/configure-ssh.sh"
    desc: Configure SSH settings

  configure-terminal:
    cmd: "{{.ROOT_DIR}}/scripts/windows/configure-terminal.sh"
    desc: Configure Windows Terminal

  configure-vscode:
    cmd: "{{.ROOT_DIR}}/scripts/windows/configure-vscode.sh"
    desc: Configure Visual Studio Code

  default:
    cmds:
      - task: configure
      - task: install
    desc: Default task (configure then install)

  install:
    cmds:
      - task: install-apps
      - task: install-nerd-fonts
    desc: Install applications and fonts

  install-apps:
    cmd: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command 'Start-Process -FilePath "winget" -ArgumentList "install {{range .apps}}{{.}} {{end}}" -Verb RunAs -Wait'
    desc: Install applications via winget

  install-nerd-fonts:
    cmd: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command 'Start-Process powershell -ArgumentList "refreshenv; choco install {{range .fonts}}nerd-fonts-{{.}} {{end}} -y" -Verb RunAs -Wait'
    desc: Install Nerd fonts via Chocolatey
    status:
      - |
        {{range .fonts}}
        ls /mnt/c/Windows/Fonts | grep -qi "{{.}}"
        {{end}}

vars:
  HOSTNAME: COLOSSUS
  apps:
    - Brave.Brave # Secure, fast & private web browser with ad blocker
    - Chocolatey.Chocolatey # Software management automation for Windows
    - Doist.Todoist # To-do list and task manager
    - DuckDuckGo.DesktopBrowser # Privacy-focused web browser
    - Git.Git # Distributed version control system
    - Microsoft.PowerToys # Set of utilities for power users
    - Microsoft.VisualStudioCode # Code editor redefined and optimized for building and debugging
    - Microsoft.WindowsTerminal # Modern terminal application for command-line tools
    - Rufus.Rufus # Create bootable USB drives the easy way
    - Syncthing.Syncthing # Open source continuous file synchronization
    - Zoom.Zoom # Video conferencing and web conferencing service
    - mpv.net # Modern media player for Windows

  fonts:
    - JetBrainsMono

version: 3
