# yaml-language-server: $schema=https://taskfile.dev/schema.json

tasks:
  default:
    cmds:
      - task: configure-terminal
      - task: install-apps
      - task: install-nerd-fonts

  configure-terminal:
    cmd: |
      WSLPATH=$(wslpath -w ~/.config/windows-terminal/settings.json)
      powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Copy-Item -Path '$WSLPATH' -Destination \"\$([Environment]::GetEnvironmentVariable('LOCALAPPDATA'))\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json\" -Force"

  install-apps:
    cmd: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command 'Start-Process -FilePath "winget" -ArgumentList "install {{range .apps}}{{.}} {{end}}" -Verb RunAs -Wait'

  install-nerd-fonts:
    cmd: powershell.exe -NoProfile -ExecutionPolicy Bypass -Command 'Start-Process powershell -ArgumentList "refreshenv; choco install nerd-fonts-firacode nerd-fonts-meslo nerd-fonts-jetbrainsmono -y" -Verb RunAs -Wait'

vars:
  apps:
    - Chocolatey.Chocolatey
    - Git.Git
    - Microsoft.PowerToys
    - Microsoft.VisualStudioCode
    - Microsoft.WindowsTerminal
    - Mozilla.Firefox
    - Rufus.Rufus
    - Syncthing.Syncthing
    - Zoom.Zoom
    - mpv.net

version: 3
