# src/cli.sh - CLI helper subcommand for jsh
# Provides: discover, completions, help
#
# Usage: jsh cli <command> [options]
#
# shellcheck shell=bash

# =============================================================================
# Dependencies
# =============================================================================

# Source the CLI framework library
# shellcheck disable=SC1091
source "${JSH_DIR}/lib/cli.sh" 2>/dev/null || {
    error "Failed to load lib/cli.sh"
    return 1
}

# =============================================================================
# Commands
# =============================================================================

# Discover all scripts with @name metadata
_cmd_cli_discover() {
    local search_dir="${JSH_DIR}/bin"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -d|--dir)
                search_dir="$2"
                shift 2
                ;;
            *)
                shift
                ;;
        esac
    done

    printf "%sDISCOVERED CLI SCRIPTS%s\n\n" "${BOLD}" "${RST}"
    printf "%-20s %-12s %s\n" "NAME" "VERSION" "PATH"
    printf "%s\n" "$(printf '%.0s-' {1..60})"

    local count=0
    while IFS=$'\t' read -r name path; do
        if [[ -n "${name}" ]]; then
            # Get version (|| true to handle grep not finding a match)
            local version
            version=$(head -50 "${path}" 2>/dev/null | grep -m1 "^# @version " | sed 's/^# @version //' || true)
            version="${version:-?}"

            # Get relative path
            local rel_path="${path#"${JSH_DIR}"/}"

            printf "%-20s %-12s %s\n" "${name}" "${version}" "${rel_path}"
            ((++count))  # Use pre-increment to avoid set -e failure when count=0
        fi
    done < <(cli_discover "${search_dir}")

    printf "\n%sFound %d scripts with metadata%s\n" "${DIM}" "${count}" "${RST}"
}

# Generate completions for all discovered scripts
_cmd_cli_completions() {
    local search_dir="${JSH_DIR}/bin"
    local shell_type="zsh"
    local output_file=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -d|--dir)
                search_dir="$2"
                shift 2
                ;;
            -s|--shell)
                shell_type="$2"
                shift 2
                ;;
            -o|--output)
                output_file="$2"
                shift 2
                ;;
            *)
                shift
                ;;
        esac
    done

    local tmp_output=""
    if [[ -n "${output_file}" ]]; then
        tmp_output=$(mktemp)
    fi

    # Header
    {
        printf "# Auto-generated by: jsh cli completions -s %s\n" "${shell_type}"
        printf "# Generated: %s\n\n" "$(date -Iseconds)"
    } >> "${tmp_output:-/dev/stdout}"

    local count=0
    while IFS=$'\t' read -r name path; do
        if [[ -n "${name}" ]]; then
            info "Generating completions for: ${name}"

            # Source the cli.sh and parse the target script
            (
                source "${JSH_DIR}/lib/cli.sh"
                cli_parse "${path}"
                cli_completions "${shell_type}"
                printf "\n"
            ) >> "${tmp_output:-/dev/stdout}"

            ((count++))
        fi
    done < <(cli_discover "${search_dir}")

    if [[ -n "${output_file}" ]]; then
        mv "${tmp_output}" "${output_file}"
        success "Generated completions for ${count} scripts -> ${output_file}"
    else
        printf "\n# Generated completions for %d scripts\n" "${count}"
    fi
}

# Show help for a specific script
_cmd_cli_help() {
    local script_name="${1:-}"

    if [[ -z "${script_name}" ]]; then
        die "Usage: jsh cli help <script-name>"
    fi

    # Find the script
    local script_path=""
    while IFS=$'\t' read -r name path; do
        if [[ "${name}" == "${script_name}" ]]; then
            script_path="${path}"
            break
        fi
    done < <(cli_discover "${JSH_DIR}/bin")

    if [[ -z "${script_path}" ]]; then
        die "Script not found: ${script_name}"
    fi

    # Parse and show help
    cli_parse "${script_path}"
    cli_help
}

# =============================================================================
# Main Entry Point
# =============================================================================

# shellcheck disable=SC2120  # Function handles zero args (shows help)
cmd_cli() {
    local cmd="${1:-}"

    if [[ -z "${cmd}" ]]; then
        echo "${BOLD}jsh cli${RST} - CLI helper for script discovery and completions"
        echo ""
        echo "${BOLD}USAGE:${RST}"
        echo "    jsh cli <command> [options]"
        echo ""
        echo "${BOLD}COMMANDS:${RST}"
        echo "    ${CYAN}discover${RST}      Find all scripts with @name metadata"
        echo "    ${CYAN}completions${RST}   Generate shell completions for discovered scripts"
        echo "    ${CYAN}help${RST}          Show help for a specific script"
        echo ""
        echo "${BOLD}OPTIONS:${RST}"
        echo "    ${CYAN}-d, --dir${RST} <DIR>    Directory to search (default: bin/)"
        echo "    ${CYAN}-s, --shell${RST} <SH>   Shell type: zsh, bash (default: zsh)"
        echo "    ${CYAN}-o, --output${RST} <F>   Output file (default: stdout)"
        echo ""
        echo "${BOLD}EXAMPLES:${RST}"
        echo "    jsh cli discover"
        echo "    jsh cli completions -s zsh -o _jsh_scripts"
        echo "    jsh cli help cafe"
        return 0
    fi

    shift

    case "${cmd}" in
        -h|--help|help)
            if [[ $# -gt 0 ]]; then
                _cmd_cli_help "$@"
            else
                cmd_cli  # Show usage  # shellcheck disable=SC2119
            fi
            ;;
        discover|d)
            _cmd_cli_discover "$@"
            ;;
        completions|comp|c)
            _cmd_cli_completions "$@"
            ;;
        *)
            die "Unknown command: ${cmd} (use 'jsh cli' for usage)"
            ;;
    esac
}
